package com.example.ssafesta.auth;

import com.example.ssafesta.user.NicknamePolicy;
import com.example.ssafesta.user.OAuthIdentity;
import com.example.ssafesta.user.OAuthIdentityRepository;
import com.example.ssafesta.user.OAuthProvider;
import com.example.ssafesta.user.User;
import com.example.ssafesta.user.UserRepository;
import com.example.ssafesta.wallet.WalletService;
import java.sql.SQLException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class RegistrationService {

    private static final Logger log = LoggerFactory.getLogger(RegistrationService.class);

    /** SQLState for a unique violation — the one integrity failure here that is not our bug. */
    private static final String UNIQUE_VIOLATION = "23505";

    private final UserRepository userRepository;
    private final OAuthIdentityRepository identityRepository;
    private final NicknamePolicy nicknamePolicy;
    private final WalletService wallets;

    public RegistrationService(UserRepository userRepository, OAuthIdentityRepository identityRepository,
                               NicknamePolicy nicknamePolicy, WalletService wallets) {
        this.userRepository = userRepository;
        this.identityRepository = identityRepository;
        this.nicknamePolicy = nicknamePolicy;
        this.wallets = wallets;
    }

    @Transactional
    public RegistrationResult complete(OAuthProvider provider, String providerSubject, String nickname) {
        return identityRepository.findByProviderAndProviderSubject(provider, providerSubject)
                .map(identity -> new RegistrationResult(identity.getUser().getId(), false))
                .orElseGet(() -> createMember(provider, providerSubject, nickname));
    }

    private RegistrationResult createMember(OAuthProvider provider, String providerSubject, String nickname) {
        nicknamePolicy.validate(nickname);
        if (userRepository.existsByNickname(nickname)) {
            throw new DuplicateNicknameException();
        }
        User user;
        try {
            user = userRepository.save(new User(nickname));
            identityRepository.save(new OAuthIdentity(user, provider, providerSubject));
        } catch (DataIntegrityViolationException exception) {
            throw asSignupRaceOrRethrow(exception);
        }
        // Same transaction as the member row: a member must never exist without a wallet, and the
        // signup grant must not be able to land twice (spec 003 FR-002). Outside the catch, though —
        // this user was created a line ago, so nothing here can be someone else getting there first.
        wallets.openWallet(user.getId());
        return new RegistrationResult(user.getId(), true);
    }

    /**
     * Only a <b>unique</b> violation is a race; every other integrity failure is a fault of ours.
     *
     * <p>The distinction matters because the two need opposite answers. Another signup taking the
     * nickname — or the same identity — between the check above and the insert is recoverable, and
     * the caller is told to try again. A foreign key, a NOT NULL or a CHECK failing is a bug in this
     * code: retrying can never fix it, so telling the caller to retry would loop them forever, and
     * answering 409 would bury a server fault in a status nobody investigates. Those are rethrown to
     * become a 500 that is logged loudly (T-24).
     *
     * <p>Matched on SQLState {@code 23505}, the standard code for a unique violation, rather than on
     * our own constraint names — those are generated by PostgreSQL and would silently stop matching
     * if a migration ever renamed one.
     *
     * <p>SQLState alone is not enough to make "unique violation" mean "race"; the <b>scope</b> of the
     * catch is what does that. It covers exactly the two inserts another signup can collide with, and
     * between them those tables carry only three unique constraints — the nickname, and the two on
     * {@code oauth_identities} — every one of which is a second signup arriving first. The wallet
     * insert sits outside it: that row is keyed on a user created a line earlier, so a unique
     * violation there is our bug and has to stay a 500. Catching it too was the wider version of this
     * same masking (raised in review of !56).
     *
     * <p>A nickname race gets {@code REGISTRATION_CONFLICT} rather than {@code NICKNAME_DUPLICATED}
     * because this code cannot tell which unique index fired without the constraint name. That is
     * survivable: retrying the same nickname reaches the check above and comes back as
     * {@code NICKNAME_DUPLICATED}, which is the right guidance. The retry converges.
     */
    private RuntimeException asSignupRaceOrRethrow(DataIntegrityViolationException exception) {
        if (!isUniqueViolation(exception)) {
            return exception;
        }
        log.warn("가입 경합으로 거절했습니다 — 동시에 같은 닉네임 또는 같은 소셜 계정이 들어왔습니다.", exception);
        return new RegistrationConflictException();
    }

    private static boolean isUniqueViolation(Throwable exception) {
        for (Throwable cause = exception; cause != null; cause = cause.getCause()) {
            if (cause instanceof SQLException sql && UNIQUE_VIOLATION.equals(sql.getSQLState())) {
                return true;
            }
        }
        return false;
    }

    public record RegistrationResult(Long userId, boolean newlyRegistered) {
    }
}
