-- spec 019 — Game Studio 저장 경계 (BE/data-model.md, contracts/game-api.md v1.0)
--
-- 세 테이블의 역할이 다르다: games는 소유·공개 상태, game_drafts는 편집 중인 하나,
-- game_published_versions는 되돌릴 수 없는 이력이다. 005 Layout이 같은 갈래를 이미 쓰고 있어
-- 컬럼 이름과 제약 모양을 그대로 맞췄다 — 두 도메인이 다른 관례를 갖는 것이 더 비싸다.

CREATE TABLE games (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id BIGINT NOT NULL REFERENCES users(id),
  title VARCHAR(100) NOT NULL,
  -- PRIVATE이 기본값이다. 만들자마자 공개되는 쪽이 놀랍다 (contracts §게임 생성).
  visibility VARCHAR(20) NOT NULL DEFAULT 'PRIVATE' CHECK (visibility IN ('PRIVATE', 'PUBLIC')),
  -- NULL은 "공개된 것이 없음"이다. MAX(version_no)로 유도하면 공개 중단이 표현되지 않는다.
  published_version INTEGER,
  -- 일반 삭제의 soft-delete marker. 회원 탈퇴 hard delete는 행을 지운다 (FR-040).
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 활성 Game 20개 / 삭제본 5개 상한(contracts §게임 생성·§삭제본 보관)은 값이 서버 설정이라
-- CHECK로 굳히지 않는다. 대신 두 세는 질의가 인덱스를 타게 한다.
CREATE INDEX ix_games_owner_active ON games(owner_user_id) WHERE deleted_at IS NULL;
CREATE INDEX ix_games_owner_deleted ON games(owner_user_id, deleted_at) WHERE deleted_at IS NOT NULL;

CREATE TABLE game_drafts (
  -- PK가 game_id라서 "Game당 Draft는 최대 하나"가 서비스가 기억할 규칙이 아니라 스키마의 사실이다.
  game_id BIGINT PRIMARY KEY REFERENCES games(id),
  -- 019는 schemaVersion이 '1.0.0'·'1.1.0' 문자열이다. 005의 INTEGER와 다른 이유는 계약이 다르다.
  schema_version VARCHAR(20) NOT NULL,
  -- 서버가 발급하는 카운터. 최초 저장이 1이고 expectedRevision 0이 그 생성을 뜻한다.
  revision INTEGER NOT NULL DEFAULT 0 CHECK (revision >= 0),
  project_json JSONB NOT NULL,
  updated_by_user_id BIGINT NOT NULL REFERENCES users(id),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE game_published_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id BIGINT NOT NULL REFERENCES games(id),
  version_no INTEGER NOT NULL CHECK (version_no > 0),
  schema_version VARCHAR(20) NOT NULL,
  project_json JSONB NOT NULL,
  published_by_user_id BIGINT NOT NULL REFERENCES users(id),
  published_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  -- 동시 Publish가 같은 회차를 쓰는 것을 DB가 막는다. 애플리케이션의 MAX+1은 경합에서 안전하지 않다.
  UNIQUE(game_id, version_no)
);

-- 포인터가 실재하지 않는 회차를 가리키는 것을 DB가 막고, NULL일 때는 MATCH SIMPLE 규칙으로
-- 검사가 면제된다 — "공개 중단"과 "무결성"이 제약 하나로 성립한다 (V8의 booths와 같은 모양).
--
-- ON DELETE SET NULL에 컬럼 목록이 붙은 이유는 V8과 동일하다:
--   ① 목록이 없으면 PostgreSQL이 FK의 모든 컬럼을 NULL로 만들고, 여기에는 games.id(PK)가
--      포함되므로 NOT NULL 위반으로 실패한다.
--   ② 회원 탈퇴가 game_published_versions를 games보다 먼저 지울 때, 포인터가 그 회차를
--      가리키고 있으면 FK가 삭제를 막는다. 삭제 순서를 코드로 관리하는 대신 제약이 정리한다.
ALTER TABLE games
    ADD CONSTRAINT fk_games_published_version
    FOREIGN KEY (id, published_version)
    REFERENCES game_published_versions (game_id, version_no)
    ON DELETE SET NULL (published_version);
