-- spec 019 — 사용자 업로드 Game Asset (contracts/game-asset-upload.md §8, #69)
--
-- Asset metadata 와 binary 를 GameProject JSONB 밖에 둔다 (계약 원칙 8). project_json 의
-- assets[].source 는 지금도 문자열 그대로 저장되고 있고 이 테이블이 더하는 것은 그 문자열이
-- 가리키는 실물의 위치·검증 상태·소유권이다.
--
-- 저장 위치는 Postgres 다. 계약 §8 은 provider·object_key 로 객체 저장소를 전제했지만,
-- 이 경로의 소비자는 React 웹 런타임 하나이고(Unity C# 에 GAME_PORTAL 0건) /content 도
-- Spring 이 바이트를 내야 한다 — FE 가 <img src> 가 아니라 인증 fetch 로 받기 때문이다
-- (remoteAssetRepository.ts). 그러면 presigned URL·CORS·불변 키 승격이 전부 사라진다.
-- provider·object_key 컬럼은 남겨 둔다: R2 가 준비되면 새 행을 provider='R2' 로 쓰고
-- 기존 행을 백필하는 것으로 끝나고 스키마 변경이 없다.

CREATE TABLE game_assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id BIGINT NOT NULL REFERENCES games(id),

  -- 서버가 발급한다. 클라이언트가 제시한 id 는 받지 않는다 — 서버가 소유권과 유효성을
  -- 보증해야 하는 식별자를 클라이언트가 정하면 그 보증의 근거가 사라진다 (계약 §2).
  -- 형식은 FE 의 STABLE_ID 정규식 ^[A-Za-z][A-Za-z0-9_-]{0,63}$ 를 만족해야 한다.
  asset_id VARCHAR(64) NOT NULL,

  kind VARCHAR(20) NOT NULL CHECK (kind IN ('IMAGE', 'TILESET')),
  status VARCHAR(20) NOT NULL CHECK (status IN ('UPLOADING', 'READY', 'FAILED')),

  -- 검증으로 확정된 실제값. UPLOADING 동안은 아직 모르므로 NULL 이다.
  -- 선언값(declared_*)과 구분한다 — 응답 헤더에 나가는 것은 이쪽이어야 하고,
  -- 선언값을 되돌려주면 위장 MIME 이 그대로 브라우저로 간다.
  content_type VARCHAR(100),
  byte_size BIGINT CHECK (byte_size >= 0),
  width INTEGER CHECK (width > 0),
  height INTEGER CHECK (height > 0),
  sha256 VARCHAR(64),

  -- 저장 위치. 'DB' 는 content 에, 나머지는 object_key 에 있다.
  provider VARCHAR(20) NOT NULL CHECK (provider IN ('DB', 'R2', 'MINIO_LOCAL')),
  content BYTEA,
  object_key TEXT,

  -- FAILED 사유. 계약 §6 의 검증 rule 이름만 들어간다.
  -- 인프라 실패는 여기 오지 않는다 — 바이트가 우리 트랜잭션 안에 들어오므로
  -- "저장됐는지 알 수 없는" 실패가 없고, 검증 실패는 전부 결정적이다.
  failure_rule VARCHAR(60),

  -- 시작 요청의 선언값. complete 가 실제값과 대조한다.
  -- 저장하지 않으면 대조할 상대가 없다 — 요청 본문은 그 시점에 이미 사라졌다.
  declared_content_type VARCHAR(100) NOT NULL,
  declared_byte_size BIGINT NOT NULL CHECK (declared_byte_size >= 0),

  -- PUT 1회용 capability 토큰의 해시. 원문은 응답의 uploadUrl 에만 실리고 어디에도 남지 않는다
  -- (계약 §3.1 — uploadUrl 은 민감정보). FE 의 PUT 에는 Authorization 이 실리지 않으므로
  -- 이 토큰이 유일한 인증이다.
  upload_token_hash VARCHAR(64) NOT NULL,

  -- grant 만료(10분). PUT·complete 의 게이트이면서 quota 술어이기도 하다:
  -- 완료되지 않은 채 만료된 행은 상한을 잡지 않는다.
  upload_expires_at TIMESTAMPTZ NOT NULL,

  created_by_user_id BIGINT NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  -- 일반 삭제의 soft-delete marker. 회원 탈퇴 hard delete 는 행을 지우고,
  -- provider='DB' 에서는 그것으로 바이트까지 함께 사라진다.
  deleted_at TIMESTAMPTZ,

  -- 계약 §2 의 asset://game/{gameId}/{assetId} 와 1:1 이다. 소유권이 조회 조건 자체에
  -- 들어가므로 "이 Asset 이 이 Game 것인가" 를 서비스가 따로 기억할 규칙이 아니다.
  UNIQUE (game_id, asset_id),

  -- 두 저장 방식이 한 행에 섞이는 것을 스키마가 막는다.
  CONSTRAINT ck_game_assets_storage_exclusive
    CHECK ((provider = 'DB') = (object_key IS NULL)),
  CONSTRAINT ck_game_assets_db_only_content
    CHECK (provider = 'DB' OR content IS NULL),

  -- "READY 는 검증을 통과했다" 를 스키마의 사실로 만든다. 서비스가 일부만 채우고
  -- READY 로 올리는 경로가 생기면 여기서 실패한다 — 나중에 "치수가 없는 READY" 로
  -- 드러나는 것보다 낫다.
  CONSTRAINT ck_game_assets_ready_verified
    CHECK (status <> 'READY' OR (content_type IS NOT NULL AND byte_size IS NOT NULL
           AND width IS NOT NULL AND height IS NOT NULL AND sha256 IS NOT NULL)),
  CONSTRAINT ck_game_assets_ready_has_bytes
    CHECK (status <> 'READY' OR provider <> 'DB' OR content IS NOT NULL),

  -- FAILED 는 왜 실패했는지를 반드시 갖는다. 조용히 실패 상태로 두면 T-24 와 같은 모양이 된다.
  CONSTRAINT ck_game_assets_failed_has_rule
    CHECK (status <> 'FAILED' OR failure_rule IS NOT NULL)
);

-- quota 카운트(READY + 유효한 UPLOADING), 죽은 행 청소, Draft/Publish 검증 스냅샷 조회가
-- 전부 이 술어를 탄다.
CREATE INDEX ix_game_assets_game_live ON game_assets(game_id) WHERE deleted_at IS NULL;
