-- spec 019 — 사용자 업로드 Game Asset (contracts/game-asset-upload.md §8, #69)
--
-- Asset metadata 와 binary 를 GameProject JSONB 밖에 둔다 (계약 원칙 8). project_json 의
-- assets[].source 는 지금도 문자열 그대로 저장되고 있고 이 테이블이 더하는 것은 그 문자열이
-- 가리키는 실물의 위치·검증 상태·소유권이다.
--
-- 저장 위치는 R2(객체 저장소)다. 업로드는 presigned PUT 으로 브라우저가 직접 올리고,
-- 조회(GET /content)는 Spring 이 R2 에서 읽어 바이트를 중계한다 — 302 리다이렉트가 아니다.
-- 이유: object-storage-contract.md §CORS 가 버킷에 AllowedMethods: PUT 만 허용하므로
-- FE 의 인증 fetch(remoteAssetRepository.ts)가 R2 로 리다이렉트되면 GET 이 CORS 에서 죽는다.
--
-- provider·storage_bucket 을 행에 적는다. 읽기는 "지금 활성 provider" 가 아니라 그 행이
-- 적어 둔 곳을 따라가야 한다 — MinIO fallback 으로 활성이 바뀌어도 R2 에 남은 옛 객체는
-- 계속 R2 에서 읽힌다 (spec 007 FR-030 저장소 Provider 불변식과 같은 규칙).

CREATE TABLE game_assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id BIGINT NOT NULL REFERENCES games(id),

  -- 서버가 발급한다. 클라이언트가 제시한 id 는 받지 않는다 — 서버가 소유권과 유효성을
  -- 보증해야 하는 식별자를 클라이언트가 정하면 그 보증의 근거가 사라진다 (계약 §2).
  -- 형식은 FE 의 STABLE_ID 정규식 ^[A-Za-z][A-Za-z0-9_-]{0,63}$ 를 만족해야 한다.
  asset_id VARCHAR(64) NOT NULL,

  kind VARCHAR(20) NOT NULL CHECK (kind IN ('IMAGE', 'TILESET')),
  status VARCHAR(20) NOT NULL CHECK (status IN ('UPLOADING', 'READY', 'FAILED')),

  -- 검증으로 확정된 실제값. UPLOADING 동안은 아직 모르므로 NULL 이다.
  -- 선언값(declared_*)과 구분한다 — 응답 헤더에 나가는 것은 이쪽이어야 하고,
  -- 선언값을 되돌려주면 위장 MIME 이 그대로 브라우저로 간다.
  content_type VARCHAR(100),
  byte_size BIGINT CHECK (byte_size >= 0),
  width INTEGER CHECK (width > 0),
  height INTEGER CHECK (height > 0),
  sha256 VARCHAR(64),

  -- 저장 위치. 발급 시점의 활성 provider·bucket 을 박아 두고 이후 읽기·삭제가 이것을 따른다.
  provider VARCHAR(20) NOT NULL CHECK (provider IN ('R2', 'MINIO_LOCAL')),
  storage_bucket TEXT NOT NULL,
  object_key TEXT NOT NULL,

  -- FAILED 사유. 계약 §6 의 검증 rule 이름만 들어간다.
  -- 저장소가 답을 못 주는 실패(503)는 여기 오지 않는다 — 그 경우 행은 UPLOADING 그대로 두고
  -- 재시도를 허용한다. FAILED 는 바이트를 읽어 본 뒤 결정적으로 거절한 것만이다.
  failure_rule VARCHAR(60),

  -- 시작 요청의 선언값. complete 가 실제값과 대조한다.
  -- 저장하지 않으면 대조할 상대가 없다 — 요청 본문은 그 시점에 이미 사라졌다.
  declared_content_type VARCHAR(100) NOT NULL,
  declared_byte_size BIGINT NOT NULL CHECK (declared_byte_size >= 0),

  -- grant 만료(10분). presigned URL 의 서명 수명과 같은 값으로 발급한다 — 서명이 더 길면
  -- 이 행이 이미 거절한 뒤에 바이트가 도착해 아무도 가리키지 않는 객체가 남는다.
  -- complete 의 게이트이면서 quota 술어이기도 하다:
  -- 완료되지 않은 채 만료된 행은 상한을 잡지 않는다.
  upload_expires_at TIMESTAMPTZ NOT NULL,

  created_by_user_id BIGINT NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  -- 일반 삭제의 soft-delete marker. 객체는 남는다 — 되살릴 수 있어야 하고, 삭제 취소가
  -- 없는 상태에서 객체를 먼저 지우면 soft 가 아니다.
  deleted_at TIMESTAMPTZ,

  -- 계약 §2 의 asset://game/{gameId}/{assetId} 와 1:1 이다. 소유권이 조회 조건 자체에
  -- 들어가므로 "이 Asset 이 이 Game 것인가" 를 서비스가 따로 기억할 규칙이 아니다.
  UNIQUE (game_id, asset_id),

  -- "READY 는 검증을 통과했다" 를 스키마의 사실로 만든다. 서비스가 일부만 채우고
  -- READY 로 올리는 경로가 생기면 여기서 실패한다 — 나중에 "치수가 없는 READY" 로
  -- 드러나는 것보다 낫다.
  CONSTRAINT ck_game_assets_ready_verified
    CHECK (status <> 'READY' OR (content_type IS NOT NULL AND byte_size IS NOT NULL
           AND width IS NOT NULL AND height IS NOT NULL AND sha256 IS NOT NULL)),

  -- FAILED 는 왜 실패했는지를 반드시 갖는다. 조용히 실패 상태로 두면 T-24 와 같은 모양이 된다.
  CONSTRAINT ck_game_assets_failed_has_rule
    CHECK (status <> 'FAILED' OR failure_rule IS NOT NULL)
);

-- quota 카운트(READY + 유효한 UPLOADING), 죽은 행 청소, Draft/Publish 검증 스냅샷 조회가
-- 전부 이 술어를 탄다.
CREATE INDEX ix_game_assets_game_live ON game_assets(game_id) WHERE deleted_at IS NULL;

-- 회원 탈퇴로 행이 사라진 뒤에도 지워야 하는 객체 (계약 §7.1).
--
-- 객체 삭제는 네트워크 호출이라 탈퇴 트랜잭션 안에서 할 수 없다 — 실패하면 탈퇴 전체가
-- 되돌아가거나(사용자가 탈퇴를 못 한다) 커밋 후 실패가 조용히 사라진다(객체가 영원히 남는다).
-- 그래서 삭제할 좌표를 같은 트랜잭션에서 이 큐에 적고, sweeper 가 나중에 비운다.
-- 큐 INSERT 가 행 DELETE 와 같은 트랜잭션이어야 하는 이유가 이것이다: 하나만 성공하면
-- 고아 객체이거나 지울 수 없는 부채가 된다.
CREATE TABLE game_asset_delete_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider VARCHAR(20) NOT NULL,
  storage_bucket TEXT NOT NULL,
  object_key TEXT NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  last_error VARCHAR(200),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  -- 같은 좌표를 두 번 적어도 한 줄이다. 삭제는 멱등이므로 중복은 해롭지 않지만,
  -- 실패가 반복될 때 큐가 같은 항목으로 부푸는 것을 막는다.
  UNIQUE (provider, storage_bucket, object_key)
);

CREATE INDEX ix_game_asset_delete_queue_due ON game_asset_delete_queue(next_attempt_at);
