CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_type VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
  nickname VARCHAR(30) NOT NULL UNIQUE,
  avatar_code VARCHAR(3800),
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE oauth_identities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id), provider VARCHAR(20) NOT NULL,
  provider_subject VARCHAR(255) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(provider, provider_subject), UNIQUE(user_id, provider)
);
CREATE TABLE wallets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE REFERENCES users(id), balance INTEGER NOT NULL DEFAULT 0 CHECK(balance >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE coin_ledger_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_id BIGINT NOT NULL REFERENCES wallets(id), entry_type VARCHAR(20) NOT NULL,
  amount INTEGER NOT NULL CHECK(amount <> 0), balance_after INTEGER NOT NULL CHECK(balance_after >= 0),
  reason_type VARCHAR(40) NOT NULL, reference_type VARCHAR(40), reference_id VARCHAR(100),
  idempotency_key VARCHAR(100) NOT NULL UNIQUE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE booth_slots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, slot_code VARCHAR(30) NOT NULL UNIQUE,
  floor_no SMALLINT NOT NULL, slot_type VARCHAR(30) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE booths (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, owner_user_id BIGINT NOT NULL REFERENCES users(id),
  current_slot_id BIGINT UNIQUE, name VARCHAR(100) NOT NULL, description TEXT,
  facade_code VARCHAR(50) NOT NULL DEFAULT 'DEFAULT', homepage_url VARCHAR(2048),
  status VARCHAR(20) NOT NULL DEFAULT 'INACTIVE', created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE booths ADD CONSTRAINT fk_booths_current_slot FOREIGN KEY (current_slot_id) REFERENCES booth_slots(id);
CREATE TABLE booth_leases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, booth_id BIGINT NOT NULL REFERENCES booths(id),
  slot_id BIGINT NOT NULL REFERENCES booth_slots(id), lessee_user_id BIGINT NOT NULL REFERENCES users(id),
  status VARCHAR(20) NOT NULL, starts_at TIMESTAMPTZ NOT NULL, ends_at TIMESTAMPTZ NOT NULL,
  charged_coin INTEGER NOT NULL CHECK(charged_coin >= 0), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK(ends_at > starts_at)
);
CREATE UNIQUE INDEX ux_booth_leases_active_slot ON booth_leases(slot_id) WHERE status = 'ACTIVE';
CREATE TABLE booth_layout_drafts (
  booth_id BIGINT PRIMARY KEY REFERENCES booths(id), schema_version INTEGER NOT NULL, layout_json JSONB NOT NULL,
  revision BIGINT NOT NULL DEFAULT 0, updated_by_user_id BIGINT NOT NULL REFERENCES users(id),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE booth_layout_published_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, booth_id BIGINT NOT NULL REFERENCES booths(id),
  version_no INTEGER NOT NULL, schema_version INTEGER NOT NULL, layout_json JSONB NOT NULL,
  published_by_user_id BIGINT NOT NULL REFERENCES users(id), published_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(booth_id, version_no)
);
CREATE TABLE ai_agents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, booth_id BIGINT NOT NULL REFERENCES booths(id),
  name VARCHAR(100) NOT NULL, role_code VARCHAR(50) NOT NULL, tone_code VARCHAR(30) NOT NULL,
  system_prompt TEXT NOT NULL, response_length VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
  service_price INTEGER NOT NULL DEFAULT 0 CHECK(service_price >= 0), handoff_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  forbidden_topics JSONB, status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE ai_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, booth_id BIGINT NOT NULL REFERENCES booths(id),
  agent_id BIGINT NOT NULL REFERENCES ai_agents(id), original_filename VARCHAR(255) NOT NULL,
  content_type VARCHAR(100) NOT NULL, size_bytes BIGINT NOT NULL CHECK(size_bytes >= 0), s3_key VARCHAR(1024) NOT NULL UNIQUE,
  processing_status VARCHAR(30) NOT NULL, uploaded_by_user_id BIGINT NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE ai_document_chunks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, document_id BIGINT NOT NULL REFERENCES ai_documents(id),
  booth_id BIGINT NOT NULL REFERENCES booths(id), agent_id BIGINT NOT NULL REFERENCES ai_agents(id), chunk_no INTEGER NOT NULL,
  content TEXT NOT NULL, embedding VECTOR(1536), embedding_model_id VARCHAR(100) NOT NULL, metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(document_id, chunk_no)
);
CREATE TABLE booth_staffs (
  booth_id BIGINT NOT NULL REFERENCES booths(id), user_id BIGINT NOT NULL REFERENCES users(id), role VARCHAR(30) NOT NULL,
  joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(booth_id, user_id)
);
CREATE TABLE staff_invitations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, booth_id BIGINT NOT NULL REFERENCES booths(id),
  invited_user_id BIGINT NOT NULL REFERENCES users(id), role VARCHAR(30) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  invited_by_user_id BIGINT NOT NULL REFERENCES users(id), expires_at TIMESTAMPTZ NOT NULL, accepted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX ux_staff_invitations_pending ON staff_invitations(booth_id, invited_user_id) WHERE status = 'PENDING';
CREATE TABLE consultations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, booth_id BIGINT NOT NULL REFERENCES booths(id),
  visitor_user_id BIGINT REFERENCES users(id), agent_id BIGINT REFERENCES ai_agents(id), staff_user_id BIGINT REFERENCES users(id),
  ai_conversation_id VARCHAR(100), summary TEXT, status VARCHAR(20) NOT NULL DEFAULT 'REQUESTED',
  requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, accepted_at TIMESTAMPTZ, ended_at TIMESTAMPTZ
);
CREATE TABLE consultation_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, consultation_id BIGINT NOT NULL REFERENCES consultations(id),
  sender_user_id BIGINT NOT NULL REFERENCES users(id), content TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, booth_id BIGINT NOT NULL REFERENCES booths(id),
  name VARCHAR(100) NOT NULL, description TEXT, thumbnail_url VARCHAR(2048), video_url VARCHAR(2048),
  deploy_url VARCHAR(2048), git_url VARCHAR(2048), portfolio_url VARCHAR(2048),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE project_likes (
  project_id BIGINT NOT NULL REFERENCES projects(id), user_id BIGINT NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(project_id, user_id)
);
CREATE TABLE surveys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, booth_id BIGINT NOT NULL REFERENCES booths(id),
  title VARCHAR(200) NOT NULL, description TEXT, reward_coin INTEGER NOT NULL DEFAULT 0 CHECK(reward_coin >= 0),
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', starts_at TIMESTAMPTZ, ends_at TIMESTAMPTZ,
  created_by_user_id BIGINT NOT NULL REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, CHECK(ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at)
);
CREATE TABLE survey_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, survey_id BIGINT NOT NULL REFERENCES surveys(id),
  question_type VARCHAR(30) NOT NULL, question_text TEXT NOT NULL, is_required BOOLEAN NOT NULL DEFAULT FALSE,
  display_order SMALLINT NOT NULL, UNIQUE(survey_id, display_order)
);
CREATE TABLE survey_options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, question_id BIGINT NOT NULL REFERENCES survey_questions(id),
  option_text VARCHAR(500) NOT NULL, display_order SMALLINT NOT NULL, UNIQUE(question_id, display_order)
);
CREATE TABLE survey_responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, survey_id BIGINT NOT NULL REFERENCES surveys(id),
  respondent_user_id BIGINT NOT NULL REFERENCES users(id), reward_ledger_entry_id BIGINT UNIQUE REFERENCES coin_ledger_entries(id),
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(survey_id, respondent_user_id)
);
CREATE TABLE survey_answers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, response_id BIGINT NOT NULL REFERENCES survey_responses(id),
  question_id BIGINT NOT NULL REFERENCES survey_questions(id), text_answer TEXT, rating_value SMALLINT,
  UNIQUE(response_id, question_id)
);
CREATE TABLE survey_answer_options (
  answer_id BIGINT NOT NULL REFERENCES survey_answers(id), option_id BIGINT NOT NULL REFERENCES survey_options(id),
  PRIMARY KEY(answer_id, option_id)
);
CREATE TABLE catalog_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, item_code VARCHAR(50) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL,
  item_type VARCHAR(30) NOT NULL, equip_slot VARCHAR(30), price INTEGER NOT NULL CHECK(price >= 0), asset_key VARCHAR(255) NOT NULL,
  is_stackable BOOLEAN NOT NULL DEFAULT FALSE, is_on_sale BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE user_inventory_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id),
  catalog_item_id BIGINT NOT NULL REFERENCES catalog_items(id), quantity INTEGER NOT NULL DEFAULT 1 CHECK(quantity >= 0),
  acquired_via VARCHAR(30) NOT NULL, acquired_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, catalog_item_id)
);
CREATE TABLE minigame_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id),
  game_type VARCHAR(30) NOT NULL, nonce UUID NOT NULL UNIQUE, status VARCHAR(20) NOT NULL,
  target_value NUMERIC(8,3) NOT NULL, result_value NUMERIC(8,3), reward_coin INTEGER NOT NULL DEFAULT 0 CHECK(reward_coin >= 0),
  reward_ledger_entry_id BIGINT UNIQUE REFERENCES coin_ledger_entries(id),
  started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at TIMESTAMPTZ
);
CREATE TABLE booth_visit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, booth_id BIGINT NOT NULL REFERENCES booths(id),
  visitor_user_id BIGINT REFERENCES users(id), world_channel VARCHAR(50) NOT NULL,
  entered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, exited_at TIMESTAMPTZ
);
CREATE TABLE booth_daily_metrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, booth_id BIGINT NOT NULL REFERENCES booths(id), metric_date DATE NOT NULL,
  visit_count INTEGER NOT NULL DEFAULT 0, ai_conversation_count INTEGER NOT NULL DEFAULT 0,
  survey_response_count INTEGER NOT NULL DEFAULT 0, consultation_count INTEGER NOT NULL DEFAULT 0,
  project_like_count INTEGER NOT NULL DEFAULT 0, revenue_coin INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(booth_id, metric_date)
);
CREATE INDEX ix_coin_ledger_entries_wallet_created_at ON coin_ledger_entries(wallet_id, created_at DESC);
CREATE INDEX ix_booth_visit_events_booth_entered_at ON booth_visit_events(booth_id, entered_at DESC);
CREATE INDEX ix_ai_document_chunks_scope ON ai_document_chunks(booth_id, agent_id);
