-- AI 문서 Job·Chunk·Staging 스키마를 Spring 으로 이관한다 (S15P21A604-397, GitLab #119).
--
-- 문서 처리 DB 소유권이 FastAPI 에서 Spring 으로 넘어왔다. FastAPI 는 DB 자격증명 없이
-- 파싱·청킹·임베딩과 질의 임베딩만 담당하고, 결과는 내부 API 로 보낸다. 교차 DB 에서는 FK 를
-- 걸 수 없어 문서 삭제·회원 탈퇴 때마다 두 DB 를 코드로 맞춰야 했다 — 그것이 S15P21A604-262
-- (별도 DB 경계)를 뒤집은 이유다.
--
-- 스키마는 AI 파트가 2026-09-02 에 올린 초안을 따른다. 새로 설계하지 않는다. 초안대로 적용하면
-- 삭제가 막히는 자리 3곳을 2026-09-03 회신으로 확정했고, 그 확정을 이 파일이 반영한다.
--
-- 되돌리기: db/rollback/V21__rollback.sql (Flyway Community 에는 undo 가 없다).

-- ── 1. Job ────────────────────────────────────────────────────────────────────────
--
-- AI DB 원본(festa-ai/app/db/models.py)에서 callback_* 5개를 뺐다. FastAPI 가 Job 을 소유하고
-- 상태를 push 하던 시절의 컬럼이다. 지금은 finalize 호출의 HTTP 응답이 곧 전달 확인이라
-- 추적할 대상이 없다 — 그대로 옮기면 아무도 갱신하지 않는 죽은 컬럼이 된다.
CREATE TABLE ai_document_jobs (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id       BIGINT NOT NULL REFERENCES ai_documents(id) ON DELETE CASCADE,
  booth_id          BIGINT NOT NULL REFERENCES booths(id),
  agent_id          BIGINT NOT NULL REFERENCES ai_agents(id),

  source_hash       VARCHAR(64) NOT NULL,
  original_filename TEXT NOT NULL,
  content_type      VARCHAR(100) NOT NULL,
  file_size_bytes   BIGINT NOT NULL,
  storage_provider  VARCHAR(20) NOT NULL,
  storage_bucket    TEXT NOT NULL,
  object_key        TEXT NOT NULL,

  status            VARCHAR(20) NOT NULL
                      CHECK (status IN ('QUEUED','RUNNING','RETRY_WAIT','SUCCEEDED','DEAD','CANCELLED')),
  attempt_no        INTEGER NOT NULL DEFAULT 0 CHECK (attempt_no >= 0),
  max_retries       INTEGER NOT NULL DEFAULT 3 CHECK (max_retries >= 0),
  worker_id         VARCHAR(100),
  lease_expires_at  TIMESTAMPTZ,
  next_retry_at     TIMESTAMPTZ,

  last_error_code   VARCHAR(50),
  last_error        TEXT,
  chunk_count       INTEGER,

  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at       TIMESTAMPTZ
);

-- 한 문서에 살아 있는 Job 은 하나다. 부분 unique 라 끝난 Job 은 몇 개든 남는다 —
-- 재처리 이력이 곧 감사 기록이다.
CREATE UNIQUE INDEX ix_ai_document_jobs_active_document
  ON ai_document_jobs(document_id)
  WHERE status IN ('QUEUED','RUNNING','RETRY_WAIT');

CREATE INDEX ix_ai_document_jobs_pickup ON ai_document_jobs(status, next_retry_at);
CREATE INDEX ix_ai_document_jobs_lease  ON ai_document_jobs(lease_expires_at) WHERE status = 'RUNNING';

-- ── 2. Chunk 확장 ─────────────────────────────────────────────────────────────────
--
-- V1 의 테이블을 그대로 쓴다. FK 대상과 인덱스가 이미 있고 쓰는 코드가 없다.
ALTER TABLE ai_document_chunks
  -- FK 를 걸지 않는다 (2026-09-03 AI 파트 확정). Job 이 문서 CASCADE 로 지워질 때
  -- 이미 searchable=TRUE 로 나간 청크의 출처 추적이 끊기면 안 된다. 값만 남긴다.
  ADD COLUMN job_id      BIGINT,
  ADD COLUMN page_number INTEGER,
  ADD COLUMN section     TEXT,
  -- finalize 가 교체를 마친 뒤에만 TRUE 로 올린다. 검색은 이 칸만 본다 —
  -- 절반만 들어온 청크가 답변에 인용되지 않게 하는 것이 이 칸의 목적이다.
  ADD COLUMN searchable  BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE ai_document_chunks
  ALTER COLUMN embedding_model_id TYPE TEXT,
  DROP COLUMN metadata;

-- 임베딩 없는 청크를 만들지 않는다 (2026-09-03 AI 파트 확정 — 원본 모델도 NOT NULL 이다).
-- staging → finalize 에서 완성된 값으로 한 번에 쓴다. 테이블에 쓰는 코드가 아직 없어
-- 행이 없다. 행이 있으면 여기서 시끄럽게 실패하는 것이 맞다 (V15·V17 과 같은 판단).
ALTER TABLE ai_document_chunks
  ALTER COLUMN embedding SET NOT NULL;

-- V1 은 ON DELETE 절 없이(NO ACTION) FK 를 만들었다. 그대로 두면 문서를 지울 때 청크 FK 가
-- 삭제를 막는다 — Job 만 CASCADE 로 지워지고 청크가 남는 어긋난 상태가 된다.
-- 이름은 Postgres 가 인라인 REFERENCES 에 붙이는 기본값이다.
ALTER TABLE ai_document_chunks
  DROP CONSTRAINT ai_document_chunks_document_id_fkey;
ALTER TABLE ai_document_chunks
  ADD CONSTRAINT ai_document_chunks_document_id_fkey
    FOREIGN KEY (document_id) REFERENCES ai_documents(id) ON DELETE CASCADE;

-- ── 3. Staging ────────────────────────────────────────────────────────────────────
--
-- batch 재전송을 멱등하게 받는 자리다. PK 가 (job_id, batch_seq, chunk_no) 라
-- ON CONFLICT DO NOTHING 으로 같은 batch 를 몇 번 받아도 결과가 같다.
-- TTL 스케줄러를 두지 않는다 — finalize 성공·CANCELLED·DEAD 에서 job_id 로 지운다.
CREATE TABLE ai_document_chunk_staging (
  job_id             BIGINT NOT NULL REFERENCES ai_document_jobs(id) ON DELETE CASCADE,
  batch_seq          INTEGER NOT NULL,
  chunk_no           INTEGER NOT NULL,
  content            TEXT NOT NULL,
  embedding          VECTOR(1536) NOT NULL,
  embedding_model_id TEXT NOT NULL,
  page_number        INTEGER,
  section            TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (job_id, batch_seq, chunk_no)
);

-- ── 4. 벡터 인덱스 ────────────────────────────────────────────────────────────────
--
-- ⚠️ 연산자 클래스는 잠정이다. 코사인(<=>)을 고른 근거는 spikes/ai-rag 의 실험 코드가
-- 그것을 써 왔다는 것뿐이고, 서비스용 임베딩 모델 ID 는 아직 미확정이다
-- (festa-ai/app/core/config.py 의 EMBEDDING_MODEL_ID 가 optional·기본값 없음).
--
-- S15P21A604-373 (RAG 최종 모델·검색 파라미터 ADR)에서 거리 기준이 내적(vector_ip_ops)이나
-- L2(vector_l2_ops)로 정해지면 이 인덱스를 DROP 하고 그 연산자로 다시 만들어야 한다.
-- 지금은 테이블이 비어 있어 재생성 비용이 사실상 없다 — 데이터가 쌓인 뒤에는 다르다.
--
-- 차원 1536 은 헌법 18조·FR-009 로 고정이므로 바뀌지 않는다.
CREATE INDEX ix_ai_document_chunks_embedding_cosine
  ON ai_document_chunks USING hnsw (embedding vector_cosine_ops);
