-- Infra 가 실행한 R2/MinIO reconcile 결과를 Spring 이 소유한다 (spec 007 FR-035, S15P21A604-500,
-- GitLab #100). 계약: specs/007-ai-agent-document/contracts/spring-storage-reconciliation-api.yaml
--
-- 이 표는 감사 기록이면서 동시에 두 가지 제어 데이터다.
--   · UNIQUE(run_id, document_id) 가 재전송 멱등의 근거다. 같은 키로 두 번 오면 두 번째는
--     아무것도 다시 반영하지 않고 저장된 결과를 그대로 되돌려준다.
--   · apply_result 가 "왜 반영되지 않았나"의 답이다. status 만 남기면 VERIFIED 인데 문서가 안
--     옮겨진 행 앞에서 감사가 멈춘다.
--
-- 문자열 폭은 계약에서 왔고, 계약의 값은 원본 컬럼에서 왔다 — object_key 는
-- ai_documents.s3_key VARCHAR(1024), content_type 은 ai_documents.content_type VARCHAR(100),
-- failure_reason 은 계약이 처음부터 정한 500 이다. run_id 만 계약에 상한이 없어 200 을 넣고
-- 계약에도 같이 넣었다: 아래 UNIQUE 인덱스는 B-tree 라서 상한 없는 값이 들어오면 튜플 크기
-- 한계에서 삽입이 실패한다. 검증되지 않은 길이를 인덱스 키로 삼지 않는다.
--
-- ON DELETE CASCADE 의 의미: 멱등 응답 보장은 문서가 살아 있는 동안에 한한다. 문서가 지워지면
-- 그 문서의 reconcile 이력도 함께 지워지고 같은 payload 재전송은 404 가 된다. 탈퇴 경로
-- (AccountDeletionService 의 DELETE FROM ai_documents)가 하드 삭제라 CASCADE 가 없으면 탈퇴
-- 전체가 FK 위반으로 실패한다 — 같은 파일 주석이 기록해 둔 함정이다. 자식 표인
-- ai_document_jobs(V21)도 같은 선택을 했다.
CREATE TABLE storage_reconciliation_log (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id                VARCHAR(200) NOT NULL,
  document_id           BIGINT NOT NULL REFERENCES ai_documents(id) ON DELETE CASCADE,
  object_key            VARCHAR(1024) NOT NULL,

  source_provider       VARCHAR(20) NOT NULL CHECK (source_provider IN ('R2','MINIO_LOCAL')),
  target_provider       VARCHAR(20) NOT NULL CHECK (target_provider IN ('R2','MINIO_LOCAL')),
  status                VARCHAR(20) NOT NULL CHECK (status IN ('VERIFIED','MISMATCH','MISSING')),

  -- 계약에 없는 유일한 컬럼이고 Spring 소유다. VERIFIED 를 받고도 문서를 옮기지 않은 이유를
  -- 행 자체가 말한다: APPLIED 는 반영함, LOGGED_ONLY 는 MISMATCH·MISSING 이라 반영 대상이
  -- 아님, STALE 은 문서가 그 source·object key 를 더 이상 갖지 않아 반영할 수 없음.
  apply_result          VARCHAR(20) NOT NULL CHECK (apply_result IN ('APPLIED','LOGGED_ONLY','STALE')),

  expected_size         BIGINT CHECK (expected_size >= 0),
  actual_size           BIGINT CHECK (actual_size >= 0),
  expected_content_type VARCHAR(100),
  actual_content_type   VARCHAR(100),
  expected_sha256       VARCHAR(64),
  actual_sha256         VARCHAR(64),

  attempt_count         INTEGER NOT NULL CHECK (attempt_count >= 1),
  failure_reason        VARCHAR(500),
  checked_at            TIMESTAMPTZ NOT NULL,
  resolved_at           TIMESTAMPTZ,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 멱등의 근거이자 endpoint 가 재전송을 판정할 때 타는 유일한 조회 경로다.
CREATE UNIQUE INDEX ux_storage_reconciliation_log_run_document
  ON storage_reconciliation_log(run_id, document_id);

-- FK 컬럼은 Postgres 가 자동으로 인덱싱하지 않는다. 이것이 없으면 문서 삭제의 CASCADE 가
-- 이 표를 seq scan 한다. 겸해서 "이 문서의 reconcile 이력" 감사 조회를 받는다.
CREATE INDEX ix_storage_reconciliation_log_document
  ON storage_reconciliation_log(document_id, checked_at DESC);
