-- 전역 관리자 권한 모델 (S15P21A604-743, 상위 S15P21A604-742).
--
-- 관리자 판정은 users.account_type = 'ADMIN' 을 매 요청 조회한다. JWT 의 role 클레임은 MEMBER 로
-- 둔다 — MemberPrincipal 이 "MEMBER".equals(role) 로 판정하고 컨트롤러 20여 곳이 그것을 타므로,
-- role 을 ADMIN 으로 발급하면 관리자 토큰이 게스트로 읽혀 본인 지갑·부스까지 403 MEMBER_ONLY 가
-- 된다. 매 요청 조회에는 부수 이점도 있다: 강등이 토큰 만료를 기다리지 않고 즉시 먹는다.

-- ── 1. 마스터 ───────────────────────────────────────────────────────────────
--
-- account_type 에 세 번째 값('MASTER_ADMIN')을 넣지 않는다. 승격·강등이 account_type 을 통째로
-- 덮어쓰는 칸이라, 한 칸에 두 개념을 섞으면 강등 한 번에 마스터 표시가 조용히 사라진다.
-- boolean 은 승격 로직이 건드리지 않는 자리에 있다.
ALTER TABLE users ADD COLUMN is_master BOOLEAN NOT NULL DEFAULT FALSE;

-- 마스터는 최대 1명이라는 것을 DB 가 보장한다. is_master 가 true 인 행에만 걸린 부분 유니크라
-- false 는 몇이든 상관없다. 애플리케이션 검사만으로 두면 동시 요청 두 개가 같은 검사를 통과한다.
CREATE UNIQUE INDEX ux_users_single_master ON users (is_master) WHERE is_master;

-- ── 2. 관리자 행위 감사 ─────────────────────────────────────────────────────
--
-- 승격·강등도 여기 들어간다. 권한이 번지는 경로를 기록 없이 열면 나중에 "누가 이 사람을
-- 관리자로 만들었나" 에 답할 수 없고, 정지·코인은 자기 이력이 있는데 권한 부여만 없으면
-- 그것이 가장 큰 구멍이 된다.
--
-- **FK 를 걸지 않는다.** AccountDeletionService 의 마지막 문장이 DELETE FROM users 라서,
-- target_user_id 에 FK 가 있으면 한 번이라도 승격된 계정은 강등한 뒤에도 탈퇴가 FK 위반으로
-- 실패한다. 코인 원장이 행위자를 reference_id 로만 남기는 것과 같은 관례다 — 감사는 그 시점의
-- 사실을 적는 장부이지 현재 행에 딸린 자식이 아니다.
--
-- actor_user_id = 0 은 시스템(마이그레이션)이다. 회원 id 는 1부터 발급되므로 겹치지 않는다.
CREATE TABLE admin_actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id BIGINT NOT NULL,
  action VARCHAR(40) NOT NULL,
  target_type VARCHAR(20) NOT NULL,
  target_id BIGINT,
  detail TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- "이 자원에 무슨 일이 있었나" 가 감사를 읽는 첫 번째 질문이다.
CREATE INDEX ix_admin_actions_target ON admin_actions (target_type, target_id, created_at DESC);
-- 두 번째 질문은 "이 관리자가 무엇을 했나" 다.
CREATE INDEX ix_admin_actions_actor ON admin_actions (actor_user_id, created_at DESC);

-- ── 3. 초기 마스터 시드 ─────────────────────────────────────────────────────
--
-- 닉네임 '구글 황덕' 을 가진 GOOGLE 계정 하나. nickname 이 UNIQUE 라 결과는 0행 아니면 1행이다.
--
-- provider 조건을 함께 거는 이유: 그 닉네임을 쥔 계정이 구글이 아니라면 엉뚱한 사람을 관리자로
-- 만드는 것보다 아무것도 하지 않는 편이 낫다.
--
-- **순서 주의.** 이 마이그레이션은 대상 계정이 이미 가입돼 있을 때만 의미가 있다. 0행이면
-- no-op 으로 끝나는데 Flyway 는 '적용됨' 으로 기록하므로 다시 돌지 않는다. 그때는 같은 조건의
-- UPDATE 를 다음 가용 버전으로 한 번 더 올린다(조건을 느슨하게 바꾸지 않는다).
UPDATE users
   SET account_type = 'ADMIN', is_master = TRUE, updated_at = CURRENT_TIMESTAMP
 WHERE nickname = '구글 황덕'
   AND EXISTS (SELECT 1 FROM oauth_identities oi
                WHERE oi.user_id = users.id AND oi.provider = 'GOOGLE');

INSERT INTO admin_actions (actor_user_id, action, target_type, target_id, detail)
SELECT 0, 'ADMIN_GRANT', 'USER', id, '초기 마스터 시드 (V36)'
  FROM users WHERE is_master;
