-- 이벤트 상점 — 경품 등록·구매·처리 상태 (S15P21A604-836, GitLab #217 4번).
--
-- 코인 차감(원장)과 경품 지급(처리 상태)은 별개 사건이다 — 원장에 SPEND 가 남았다고
-- 물건을 받은 것은 아니다. event_purchases.fulfillment 가 그 처리 상태를 잡고,
-- ledger_entry_id 는 참고용 역참조일 뿐 지급 여부의 근거가 아니다.

CREATE TABLE event_prizes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  price_coin INT NOT NULL CHECK (price_coin >= 0),
  -- NULL = 무제한 재고. 유한 재고는 구매 시 잠금 아래에서 차감한다.
  stock INT CHECK (stock IS NULL OR stock >= 0),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 구매 한 건. prize_id 는 FK 만 걸고 ON DELETE 는 두지 않는다 — 경품은 삭제 API 가 없고
-- 판매 중단은 active=false 로 내린다(카탈로그 아이템과 같은 관례), 구매 이력은 항상 남는다.
--
-- buyer_user_id 는 users(id) 를 참조한다. coin_ledger_entries·user_inventory_items 와 같은
-- 관례로, 탈퇴 시 AccountDeletionService 가 이 행을 먼저 지운다(FK 위반으로 탈퇴 전체가
-- 실패하는 것을 막는다) — admin_actions 처럼 행위자 없이 영구 보존하는 감사 기록이 아니라
-- 한 회원의 거래 이력이기 때문이다.
CREATE TABLE event_purchases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prize_id BIGINT NOT NULL REFERENCES event_prizes (id),
  buyer_user_id BIGINT NOT NULL REFERENCES users (id),
  quantity INT NOT NULL CHECK (quantity > 0),
  coin_spent INT NOT NULL CHECK (coin_spent >= 0),
  ledger_entry_id BIGINT REFERENCES coin_ledger_entries (id),
  -- PURCHASED -> PENDING/FULFILLED/CANCELLED, PENDING -> FULFILLED/CANCELLED.
  -- FULFILLED·CANCELLED 는 종단이다. 전이 규칙은 애플리케이션(PurchaseFulfillment)이 지킨다.
  fulfillment VARCHAR(20) NOT NULL DEFAULT 'PURCHASED',
  note TEXT,
  idempotency_key VARCHAR(100) NOT NULL,
  purchased_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX ux_event_purchases_idempotency_key ON event_purchases (idempotency_key);
CREATE INDEX ix_event_purchases_prize ON event_purchases (prize_id, purchased_at DESC);
CREATE INDEX ix_event_purchases_buyer ON event_purchases (buyer_user_id, purchased_at DESC);
-- 관리자 구매 내역 화면의 상태별 필터(계약 GitLab #217)가 쓰는 조회 순서다.
CREATE INDEX ix_event_purchases_fulfillment ON event_purchases (fulfillment, purchased_at DESC);
