-- GitLab #241 / S15P21A604-895 — 프로젝트 전시 대표 이미지(로고)의 업로드 lifecycle.
--
-- spec 009 C-03 은 "업로드 미지원, URL 참조" 였고 업로드가 필요해지면 별도 이슈로 하라고 적어
-- 두었다. 그 문을 여는 표다. projects.thumbnail_url 은 그대로 남는다 — 최종 참조는 계속 그 컬럼이
-- 갖고, 이 표는 "그 URL 이 가리키는 실물의 위치·검증 상태·소유권" 을 갖는다 (game_assets 와 같은
-- 분업이다, V18).
--
-- 업로드는 presigned PUT 으로 브라우저가 직접 올리고, 조회(GET /content)는 Spring 이 읽어 바이트를
-- 중계한다 — 302 가 아니다. 저장소 계약이 버킷에 PUT 만 허용하므로 브라우저 GET 은 CORS 에서 죽고,
-- presigned GET 을 브라우저에 주면 권한 검사보다 오래 사는 URL 이 된다.
CREATE TABLE project_logo_uploads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- 소유권 판정의 근거다. 프로젝트가 아니라 부스에 매달리는 이유: 프로젝트를 만들기 전에 로고를
  -- 올리는 흐름이 요구사항이고(#241 ①), 부스 편집 권한은 BoothAccessGuard 한 곳이 답한다.
  booth_id BIGINT NOT NULL REFERENCES booths(id),

  -- 서버가 발급한다. 클라이언트가 제시한 id 는 받지 않는다 — 소유권을 보증해야 하는 식별자를
  -- 클라이언트가 정하면 그 보증의 근거가 사라진다. 추측 불가능한 26자다.
  logo_id VARCHAR(64) NOT NULL,

  status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'READY', 'FAILED')),

  -- 검증으로 확정된 실제값. PENDING 동안은 아직 모르므로 NULL 이다. 선언값(declared_*)과 구분한다 —
  -- 응답 헤더에 나가는 것은 이쪽이어야 하고, 선언값을 되돌려주면 위장 MIME 이 그대로 브라우저로 간다.
  content_type VARCHAR(100),
  byte_size BIGINT CHECK (byte_size >= 0),
  width INTEGER CHECK (width > 0),
  height INTEGER CHECK (height > 0),
  sha256 VARCHAR(64),

  declared_content_type VARCHAR(100) NOT NULL,
  declared_byte_size BIGINT NOT NULL CHECK (declared_byte_size > 0),

  -- 발급 시점의 활성 provider·bucket 을 박아 두고 이후 읽기·삭제가 이것을 따른다. MinIO fallback 으로
  -- 활성이 바뀌어도 R2 에 남은 옛 객체는 계속 R2 에서 읽힌다 (spec 007 FR-030 과 같은 불변식).
  provider VARCHAR(20) NOT NULL CHECK (provider IN ('R2', 'MINIO_LOCAL')),
  storage_bucket TEXT NOT NULL,
  object_key TEXT NOT NULL,

  -- FAILED 사유. 검증 rule 이름만 들어간다. 저장소가 답을 못 주는 실패(503)는 여기 오지 않는다 —
  -- 그 경우 행은 PENDING 그대로 두고 재시도를 허용한다.
  failure_rule VARCHAR(60),

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMPTZ,

  -- 발급 당시 계산해 저장한다. created_at + 현재 설정으로 재계산하면 presign TTL 을 나중에 바꿨을 때
  -- 이미 발급된 grant 의 만료가 소급해 움직인다.
  expires_at TIMESTAMPTZ NOT NULL,

  -- 이 로고를 가리키던 thumbnail_url 이 다른 값으로 바뀐 시각. 참조가 끊긴 사실을 그 자리에서
  -- 적어 두고, 실제 삭제는 정리 배치가 유예 뒤에 한다. NULL 이면 "참조가 끊긴 적 없음" 이다.
  --
  -- ⚠️ 이 칸은 삭제의 근거가 아니라 후보 표식이다. 최종 판정은 삭제 실행 시점의 thumbnail_url
  -- 재조회다 — A → B → 다시 A 로 되돌리면 예약된 A 삭제가 살아 있는 이미지를 지운다.
  unreferenced_since TIMESTAMPTZ
);

CREATE UNIQUE INDEX ux_project_logo_uploads_logo_id ON project_logo_uploads (logo_id);
CREATE INDEX ix_project_logo_uploads_booth ON project_logo_uploads (booth_id, created_at DESC);
-- 정리 배치가 훑는 순서다: 만료된 PENDING · FAILED · 참조가 끊긴 READY.
CREATE INDEX ix_project_logo_uploads_status ON project_logo_uploads (status, expires_at);
