-- 피드백 제출 (S15P21A604-953).
--
-- 최초 발견 판정은 운영자가 목록을 읽고 손으로 고른다 — 같은 문제를 여러 명이 신고했는지
-- 자동으로 가려낼 근거(중복 판정 기준)가 아직 없어서다. first_found 는 그 판정을 담는 자리일
-- 뿐이고, 보상 지급은 이 표가 하지 않는다 — 기존 관리자 코인 조정(coin_ledger_entries,
-- ADMIN_ADJUSTMENT)을 그대로 쓴다.
--
-- user_id 는 users(id) 를 참조한다. 회원 자신의 제출 이력이라 event_purchases 와 같은 관례로
-- 탈퇴와 함께 지운다(AccountDeletionService) — 이 줄이 없으면 피드백을 낸 회원의 탈퇴가
-- FK 위반으로 실패한다.
CREATE TABLE feedback_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users (id),
  content TEXT NOT NULL,
  first_found BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 관리자 목록의 기본 정렬(최신순)이 쓰는 순서다.
CREATE INDEX ix_feedback_submissions_created ON feedback_submissions (created_at DESC);
