-- Balance/ledger reconciliation results (spec 003 FR-014).
-- Detection only: a run records mismatches and never corrects a balance.
CREATE TABLE coin_reconciliation_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at TIMESTAMPTZ,
  status VARCHAR(20) NOT NULL,
  checked_wallet_count INTEGER NOT NULL DEFAULT 0 CHECK(checked_wallet_count >= 0),
  mismatched_wallet_count INTEGER NOT NULL DEFAULT 0 CHECK(mismatched_wallet_count >= 0),
  mismatches JSONB,
  failure_reason TEXT
);

CREATE INDEX ix_coin_reconciliation_runs_started_at ON coin_reconciliation_runs(started_at DESC);
