apiVersion: 1
contactPoints:
  - orgId: 1
    name: mattermost-approved-anomalies
    receivers:
      - uid: mattermost-approved-anomalies
        type: slack
        disableResolveMessage: false
        settings:
          url: $__env{MATTERMOST_WEBHOOK_URL}
          recipient: "#festa-operations"
          title: '{{ template "festa.alert.title" . }}'
          text: '{{ template "festa.alert.body" . }}'
