// 8번 오락기에서 차선을 바꾸며 교통과 장애물을 피하는 횡스크롤 레이싱 게임을 실행한다.
using System.Collections.Generic;
using Festa.World;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Festa.Content.Arcade
{
    [DisallowMultipleComponent]
    public sealed class MegaPackNeonRacerMiniGame : MonoBehaviour
    {
        const float WorldY=10800f,Duration=60f;const string Root="Arcade/MegaPackNeonRacer/";
        readonly List<GameObject> _runtime=new(),_traffic=new(),_pickups=new(); static readonly float[] Lanes={-2.25f,0f,2.25f};
        Camera _camera;RenderTexture _target;Material _screenMaterial;Sprite _solid,_car,_road,_barrier,_coin;AudioClip _hit,_bonus;AudioSource _audio;Canvas _overlay;
        GameObject _player,_resultPanel;TextMeshPro _scoreText,_timeText,_speedText,_message,_preview;float _time,_speed,_spawnAt,_coinAt,_invincible,_distance,_worldY,_nitro,_nitroUntil;int _lane=1,_score,_combo,_bestCombo;bool _active,_ended;

        void Awake(){_worldY=GetComponent<ArcadeMachineInteractable>()?.MachineId=="arcade-18"?WorldY+5000f:WorldY;LoadAssets();CreateScreen();Build();PreparePreview();Show(false);InteractionFocusCamera.Released+=Released;enabled=false;}
        public bool Begin(){if(_camera==null||_screenMaterial==null||_car==null||_road==null)return false;ArcadeOverlayHudSuppressor.Acquire();NewGame();Show(true);_active=true;enabled=true;return true;}
        void Update(){if(!_active)return;if(!InteractionFocusCamera.IsFocused){Released();return;}if(_ended){if(ArcadeRetryInput.WasPressed())NewGame();return;}_time-=Time.deltaTime;if(_time<=0){Finish();return;}
            if(Input.GetKeyDown(KeyCode.W)||Input.GetKeyDown(KeyCode.UpArrow))_lane=Mathf.Min(2,_lane+1);if(Input.GetKeyDown(KeyCode.S)||Input.GetKeyDown(KeyCode.DownArrow))_lane=Mathf.Max(0,_lane-1);
            if(Input.GetKeyDown(KeyCode.Space))ActivateNitro();float throttle=(Input.GetKey(KeyCode.D)||Input.GetKey(KeyCode.RightArrow))?1:(Input.GetKey(KeyCode.A)||Input.GetKey(KeyCode.LeftArrow))?-1:0;float nitro=Time.time<_nitroUntil?4.8f:0;_speed=Mathf.MoveTowards(_speed,7.5f+throttle*3f+nitro,Time.deltaTime*(nitro>0?8f:3.5f));_distance+=_speed*Time.deltaTime;_score+=Mathf.RoundToInt(_speed*Time.deltaTime*(nitro>0?7f:4f));_invincible-=Time.deltaTime;
            _player.transform.position=Vector3.Lerp(_player.transform.position,ToWorld(new Vector2(-4.7f,Lanes[_lane])),1-Mathf.Exp(-12f*Time.deltaTime));if(Time.time>=_spawnAt)SpawnTraffic();if(Time.time>=_coinAt)SpawnCoin();MoveObjects();UpdateHud();}
        void SpawnTraffic(){bool hazard=Random.value<.25f;int lane=Random.Range(0,3);var g=SpriteObject(hazard?"Barrier":"Traffic",hazard?_barrier:_car,hazard?Color.white:new Color(1,.35f,.45f),new Vector2(6.4f,Lanes[lane]),7);SetWidth(g,hazard?1f:1.65f);if(!hazard)g.transform.rotation=Quaternion.Euler(0,0,180);g.AddComponent<RacerToken>().lane=lane;_traffic.Add(g);_spawnAt=Time.time+Mathf.Lerp(1.25f,.58f,1-_time/Duration);}
        void ActivateNitro(){if(_nitro<100f||Time.time<_nitroUntil)return;_nitro=0;_nitroUntil=Time.time+3.2f;_invincible=Mathf.Max(_invincible,3.2f);_message.text="NITRO RUSH!";Invoke(nameof(ClearMessage),.7f);Play(_bonus,.6f);}
        void SpawnCoin(){int lane=Random.Range(0,3);var g=SpriteObject("Coin",_coin,new Color(1,1,.45f),new Vector2(6.2f,Lanes[lane]),8);SetHeight(g,.7f);g.AddComponent<RacerToken>().lane=lane;_pickups.Add(g);_coinAt=Time.time+Random.Range(1.3f,2.3f);}
        void MoveObjects(){float dx=_speed*Time.deltaTime;for(int i=_traffic.Count-1;i>=0;i--){var g=_traffic[i];g.transform.position+=Vector3.left*dx;if(g.transform.position.x<-6.3f){DestroyTracked(g);_traffic.RemoveAt(i);_combo++;_nitro=Mathf.Min(100f,_nitro+8f);_bestCombo=Mathf.Max(_bestCombo,_combo);_score+=100+_combo*10;continue;}if(_invincible<=0&&g.GetComponent<RacerToken>().lane==_lane&&Mathf.Abs(g.transform.position.x-_player.transform.position.x)<1.05f){_score=Mathf.Max(0,_score-500);_combo=0;_nitro=Mathf.Max(0,_nitro-30f);_invincible=1.2f;Play(_hit,.45f);DestroyTracked(g);_traffic.RemoveAt(i);}}
            for(int i=_pickups.Count-1;i>=0;i--){var g=_pickups[i];g.transform.position+=Vector3.left*dx;if(g.transform.position.x<-6.3f){DestroyTracked(g);_pickups.RemoveAt(i);continue;}if(g.GetComponent<RacerToken>().lane==_lane&&Mathf.Abs(g.transform.position.x-_player.transform.position.x)<.9f){_score+=350;_combo+=2;_nitro=Mathf.Min(100f,_nitro+35f);Play(_bonus,.5f);DestroyTracked(g);_pickups.RemoveAt(i);}}}
        void NewGame(){CancelInvoke();ClearMoving();_lane=1;_score=_combo=_bestCombo=0;_time=Duration;_speed=7.5f;_distance=_invincible=_nitro=_nitroUntil=0;_spawnAt=Time.time+1f;_coinAt=Time.time+1.6f;_ended=false;_resultPanel.SetActive(false);_preview.gameObject.SetActive(false);_message.text="DODGE • COLLECT • CHARGE NITRO\nW/S LANES   SPACE NITRO";Invoke(nameof(ClearMessage),1.5f);UpdateHud();}
        void ClearMessage(){if(!_ended)_message.text=string.Empty;}void UpdateHud(){_scoreText.text=_score.ToString("N0");_timeText.text=Mathf.CeilToInt(_time).ToString();_speedText.text=Time.time<_nitroUntil?$"NITRO! {Mathf.Max(0,_nitroUntil-Time.time):0.0}s\n{Mathf.RoundToInt(_speed*18)} KM/H":$"{Mathf.RoundToInt(_speed*18)} KM/H\nNITRO {Mathf.RoundToInt(_nitro)}%";}
        void Finish(){_ended=true;ClearMoving();_message.text=string.Empty;_resultPanel.SetActive(true);_preview.gameObject.SetActive(true);ArcadeRankingBoard.ShowResult(this,_preview,_camera,"NEON RACER",$"FINISH   SCORE {_score:N0}\nDISTANCE {_distance:N0} m   BEST COMBO {_bestCombo}",_score);}
        void Build(){_solid=Solid();var cg=Track(new GameObject("@NeonRacerCamera"));_camera=cg.AddComponent<Camera>();_camera.orthographic=true;_camera.orthographicSize=4.5f;_camera.aspect=16f/9f;_camera.clearFlags=CameraClearFlags.SolidColor;_camera.backgroundColor=new Color(.015f,.025f,.06f);_camera.transform.position=new Vector3(0,_worldY,-10);_target=new RenderTexture(640,360,16){name="NeonRacer_640x360",filterMode=FilterMode.Bilinear};_target.Create();_camera.targetTexture=_target;
            var road=SpriteObject("Road",_road,Color.white,new Vector2(-.8f,0),0);SetWidth(road,11.6f);road.transform.localScale=new Vector3(road.transform.localScale.x,road.transform.localScale.y*2.65f,1);for(int i=0;i<4;i++)Panel(new Vector2(-.8f,-3.35f+i*2.25f),new Vector2(11.4f,.055f),new Color(.2f,.85f,1,.7f),2);_player=SpriteObject("PlayerCar",_car,new Color(.25f,1f,1f),new Vector2(-4.7f,0),9);SetWidth(_player,1.7f);
            Panel(new Vector2(6.15f,0),new Vector2(1.75f,8.2f),new Color(.035f,.09f,.2f),3);Text("NEON\nRACER",new Vector2(6.15f,3.1f),3.8f,new Color(.2f,1f,1f),out _);Text("SCORE",new Vector2(6.15f,1.65f),2.2f,Color.white,out _);Text("0",new Vector2(6.15f,1.12f),3.5f,new Color(1,.82f,.2f),out _scoreText);Text("TIME",new Vector2(6.15f,.25f),2.2f,Color.white,out _);Text("60",new Vector2(6.15f,-.28f),3.5f,new Color(.3f,1f,.85f),out _timeText);Text("135 KM/H\nCOMBO x1",new Vector2(6.15f,-1.55f),2.1f,Color.white,out _speedText);Text("W/S LANE\nA/D SPEED",new Vector2(6.15f,-3f),1.8f,new Color(.72f,.82f,1),out _);Text("",new Vector2(-.65f,0),3.1f,Color.white,out _message);_resultPanel=Panel(new Vector2(-.65f,-.05f),new Vector2(7.1f,4.9f),new Color(.01f,.025f,.07f,.97f),18);Text("",new Vector2(-.65f,-.05f),2.55f,Color.white,out _preview);BuildOverlay();_audio=Track(new GameObject("RacerAudio")).AddComponent<AudioSource>();}
        void PreparePreview(){ClearMoving();_player.transform.position=ToWorld(new Vector2(-4.7f,0));_scoreText.text="0";_timeText.text="60";_speedText.text="ARCADE 08";_message.text=string.Empty;_resultPanel.SetActive(true);_preview.gameObject.SetActive(true);ArcadeRankingBoard.ShowPreview(this,_preview,_camera,"NEON RACER\nDODGE TRAFFIC • COLLECT COINS");}
        void DestroyTracked(GameObject g){if(g==null)return;_runtime.Remove(g);Destroy(g);}void ClearMoving(){foreach(var g in _traffic)if(g!=null)DestroyTracked(g);foreach(var g in _pickups)if(g!=null)DestroyTracked(g);_traffic.Clear();_pickups.Clear();}
        void LoadAssets(){_car=Resources.Load<Sprite>(Root+"Car");_road=Resources.Load<Sprite>(Root+"Road");_barrier=Resources.Load<Sprite>(Root+"Barrier");_coin=Resources.Load<Sprite>(Root+"Coin");_hit=Resources.Load<AudioClip>(Root+"Hit");_bonus=Resources.Load<AudioClip>(Root+"Bonus");}void Play(AudioClip c,float v){if(c!=null)_audio.PlayOneShot(c,v);}
        void CreateScreen(){var power=GetComponent<ArcadeScreenPower>();foreach(var r in GetComponentsInChildren<MeshRenderer>(true)){var ms=r.sharedMaterials;for(int i=0;i<ms.Length;i++)if(ms[i]!=null&&power!=null&&power.IsScreenMaterial(ms[i])){_screenMaterial=new Material(ms[i]);_screenMaterial.SetTextureScale("_BaseMap",Vector2.one);_screenMaterial.SetTextureOffset("_BaseMap",Vector2.zero);ms[i]=_screenMaterial;r.sharedMaterials=ms;return;}}}
        void BuildOverlay(){var go=Track(new GameObject("@NeonRacerPlayCanvas",typeof(RectTransform),typeof(Canvas),typeof(CanvasScaler),typeof(GraphicRaycaster)));_overlay=go.GetComponent<Canvas>();_overlay.renderMode=RenderMode.ScreenSpaceOverlay;_overlay.sortingOrder=32000;var sc=go.GetComponent<CanvasScaler>();sc.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;sc.referenceResolution=new Vector2(1920,1080);sc.matchWidthOrHeight=.5f;var back=new GameObject("Backdrop",typeof(RectTransform),typeof(Image));back.transform.SetParent(go.transform,false);var br=back.GetComponent<RectTransform>();br.anchorMin=Vector2.zero;br.anchorMax=Vector2.one;br.offsetMin=br.offsetMax=Vector2.zero;back.GetComponent<Image>().color=Color.black;var image=new GameObject("GameScreen",typeof(RectTransform),typeof(RawImage),typeof(AspectRatioFitter));image.transform.SetParent(go.transform,false);var rect=image.GetComponent<RectTransform>();rect.anchorMin=Vector2.zero;rect.anchorMax=Vector2.one;rect.offsetMin=rect.offsetMax=Vector2.zero;image.GetComponent<RawImage>().texture=_target;var fit=image.GetComponent<AspectRatioFitter>();fit.aspectMode=AspectRatioFitter.AspectMode.FitInParent;fit.aspectRatio=16f/9f;}
        void Show(bool p){if(_overlay!=null)_overlay.gameObject.SetActive(p);if(_screenMaterial!=null)_screenMaterial.SetTexture("_BaseMap",_target);if(_preview!=null)_preview.gameObject.SetActive(!p);if(_camera!=null){_camera.enabled=p;if(!p)_camera.Render();}}void Released(){if(!_active)return;_active=false;StopAllCoroutines();CancelInvoke();ArcadeOverlayHudSuppressor.Release();if(_player!=null&&_preview!=null){PreparePreview();Show(false);}enabled=false;}
        GameObject SpriteObject(string n,Sprite s,Color c,Vector2 p,int o){var g=Track(new GameObject(n));g.transform.position=ToWorld(p);var r=g.AddComponent<SpriteRenderer>();r.sprite=s??_solid;r.color=c;r.sortingOrder=o;return g;}GameObject Panel(Vector2 p,Vector2 z,Color c,int o){var g=SpriteObject("Panel",_solid,c,p,o);g.transform.localScale=new Vector3(z.x,z.y,1);return g;}void Text(string v,Vector2 p,float s,Color c,out TextMeshPro t){var g=Track(new GameObject("Text"));g.transform.position=ToWorld(p);t=g.AddComponent<TextMeshPro>();t.text=v;t.fontSize=s;t.color=c;t.alignment=TextAlignmentOptions.Center;t.rectTransform.sizeDelta=new Vector2(8,5);t.sortingOrder=20;}Sprite Solid(){var t=new Texture2D(1,1);t.SetPixel(0,0,Color.white);t.Apply();return Sprite.Create(t,new Rect(0,0,1,1),Vector2.one*.5f,1);}static void SetHeight(GameObject g,float h){var s=g.GetComponent<SpriteRenderer>().sprite;g.transform.localScale=Vector3.one*(h/Mathf.Max(.001f,s.bounds.size.y));}static void SetWidth(GameObject g,float w){var s=g.GetComponent<SpriteRenderer>().sprite;g.transform.localScale=Vector3.one*(w/Mathf.Max(.001f,s.bounds.size.x));}GameObject Track(GameObject g){g.transform.SetParent(null,false);_runtime.Add(g);return g;}Vector3 ToWorld(Vector2 p)=>new(p.x,_worldY+p.y,0);
        void OnDestroy(){if(_active)ArcadeOverlayHudSuppressor.Release();InteractionFocusCamera.Released-=Released;ClearMoving();foreach(var g in _runtime)if(g!=null)Destroy(g);if(_target!=null){_target.Release();Destroy(_target);}if(_screenMaterial!=null)Destroy(_screenMaterial);}sealed class RacerToken:MonoBehaviour{public int lane;}
    }
}
