// 6번 오락기에서 패들 반사각과 콤보를 사용하는 네온 벽돌깨기를 실행한다.
using System.Collections;
using System.Collections.Generic;
using Festa.World;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Festa.Content.Arcade
{
    [DisallowMultipleComponent]
    public sealed class MegaPackBreakoutMiniGame : MonoBehaviour
    {
        const float WorldY=10600f,Left=-5.55f,Right=4.65f,Top=3.75f;const string Root="Arcade/MegaPackBreakout/";
        sealed class Brick{public GameObject Go;public Vector2 Pos;public int Hp;}
        readonly List<GameObject> _runtime=new();readonly List<Brick> _bricks=new();Camera _camera;RenderTexture _target;Material _screenMaterial;Sprite _solid,_paddleSprite,_ballSprite,_brickSprite;GameObject _paddle,_ball,_resultPanel;
        TextMeshPro _scoreText,_livesText,_stageText,_message,_preview;Canvas _overlay;AudioSource _audio;AudioClip _hitClip,_clearClip;Vector2 _ballPos,_velocity;float _paddleX,_serveAt,_worldY;int _score,_lives,_stage,_combo,_bestCombo,_pierceHits;bool _active,_ended,_serving;
        static readonly Color[] Colors={new(.2f,.95f,1),new(.8f,.3f,1),new(1,.35f,.55f),new(1,.75f,.18f),new(.35f,1,.45f)};

        void Awake(){_worldY=GetComponent<ArcadeMachineInteractable>()?.MachineId=="arcade-16"?WorldY+5000f:WorldY;LoadAssets();CreateScreen();Build();PreparePreview();Show(false);InteractionFocusCamera.Released+=Released;enabled=false;}
        public bool Begin(){if(_camera==null||_screenMaterial==null||_paddleSprite==null||_ballSprite==null||_brickSprite==null)return false;ArcadeOverlayHudSuppressor.Acquire();NewGame();Show(true);_active=true;enabled=true;return true;}
        void Update(){if(!_active)return;if(!InteractionFocusCamera.IsFocused){Released();return;}if(_ended){if(ArcadeRetryInput.WasPressed())NewGame();return;}float input=(Input.GetKey(KeyCode.D)||Input.GetKey(KeyCode.RightArrow)?1:0)-(Input.GetKey(KeyCode.A)||Input.GetKey(KeyCode.LeftArrow)?1:0);_paddleX=Mathf.Clamp(_paddleX+input*7.8f*Time.deltaTime,Left+1.05f,Right-1.05f);_paddle.transform.position=ToWorld(new Vector2(_paddleX,-3.25f));if(_serving){_ballPos=new Vector2(_paddleX,-2.72f);if(Time.time>=_serveAt&&(Input.GetKeyDown(KeyCode.Space)||Time.time>=_serveAt+1.2f))Serve();_ball.transform.position=ToWorld(_ballPos);return;}StepBall();}
        void StepBall(){Vector2 previous=_ballPos;_ballPos+=_velocity*Time.deltaTime;if(_ballPos.x<Left){_ballPos.x=Left;_velocity.x=Mathf.Abs(_velocity.x);HitSound();}if(_ballPos.x>Right){_ballPos.x=Right;_velocity.x=-Mathf.Abs(_velocity.x);HitSound();}if(_ballPos.y>Top){_ballPos.y=Top;_velocity.y=-Mathf.Abs(_velocity.y);HitSound();}if(_ballPos.y<-4.05f){LoseLife();return;}
            if(_velocity.y<0&&previous.y>=-2.88f&&_ballPos.y<=-2.88f&&Mathf.Abs(_ballPos.x-_paddleX)<1.15f){float offset=Mathf.Clamp((_ballPos.x-_paddleX)/1.15f,-1,1);float speed=Mathf.Min(10.8f,_velocity.magnitude+.22f);_velocity=new Vector2(offset*.82f,1).normalized*speed;_ballPos.y=-2.86f;_combo=0;HitSound();}
            for(int i=_bricks.Count-1;i>=0;i--){var b=_bricks[i];if(Mathf.Abs(_ballPos.x-b.Pos.x)>.58f||Mathf.Abs(_ballPos.y-b.Pos.y)>.3f)continue;if(_pierceHits<=0)_velocity.y*= -1;else _pierceHits--;b.Hp--;_combo++;_bestCombo=Mathf.Max(_bestCombo,_combo);_score+=100*Mathf.Clamp(_combo,1,10);if(_combo==8){_pierceHits=5;_ball.GetComponent<SpriteRenderer>().color=new Color(1f,.82f,.15f);_message.text="FIREBALL! 5 BRICKS PIERCE";StartCoroutine(ClearMessage());}if(_pierceHits<=0)_ball.GetComponent<SpriteRenderer>().color=Color.white;_scoreText.text=_score.ToString("N0");if(b.Hp<=0){DestroyTracked(b.Go);_bricks.RemoveAt(i);}else b.Go.GetComponent<SpriteRenderer>().color=Color.white*.65f;HitSound();break;}_ball.transform.position=ToWorld(_ballPos);if(_bricks.Count==0)NextStage();}
        void NewGame(){ClearBricks();_score=0;_lives=3;_stage=1;_combo=_bestCombo=_pierceHits=0;_paddleX=-.45f;_ended=false;_scoreText.text="0";_livesText.text="LIVES 3";_resultPanel.SetActive(false);_preview.gameObject.SetActive(false);_message.text="8-BRICK COMBO = FIREBALL\nA/D MOVE   SPACE SERVE";BuildStage();ReadyBall();StartCoroutine(ClearMessage());}
        IEnumerator ClearMessage(){yield return new WaitForSeconds(1.5f);if(!_ended)_message.text=string.Empty;}
        void ReadyBall(){_serving=true;_serveAt=Time.time+.35f;_ball.SetActive(true);_ballPos=new Vector2(_paddleX,-2.72f);_ball.transform.position=ToWorld(_ballPos);}
        void Serve(){_serving=false;float x=Random.Range(-.6f,.6f);_velocity=new Vector2(x,1).normalized*(6.4f+(_stage-1)*.65f);}
        void LoseLife(){_lives--;_combo=_pierceHits=0;_ball.GetComponent<SpriteRenderer>().color=Color.white;_livesText.text="LIVES "+_lives;if(_lives<=0){Finish(false);return;}ReadyBall();}
        void NextStage(){Play(_clearClip,.55f);_stage++;if(_stage>3){Finish(true);return;}_stageText.text="STAGE "+_stage;BuildStage();ReadyBall();}
        void BuildStage(){ClearBricks();for(int row=0;row<4+_stage;row++)for(int col=0;col<9;col++){Vector2 p=new(-4.9f+col*1.12f,3.15f-row*.58f);int hp=_stage>=2&&row==0?2:1;var g=SpriteObject("Brick",_brickSprite,Colors[row%Colors.Length],p,5);Scale(g,1f,.42f);_bricks.Add(new Brick{Go=g,Pos=p,Hp=hp});}_stageText.text="STAGE "+_stage;}
        void Finish(bool won){_ended=true;_serving=false;_ball.SetActive(false);_message.text=string.Empty;_resultPanel.SetActive(true);_preview.gameObject.SetActive(true);ArcadeRankingBoard.ShowResult(this,_preview,_camera,"BRICK BREAKER",$"{(won?"ALL CLEAR!":"GAME OVER")}   SCORE {_score:N0}\nBEST COMBO {_bestCombo}",_score);}
        void Build(){_solid=Solid();var cg=Track(new GameObject("@BreakoutCamera"));_camera=cg.AddComponent<Camera>();_camera.orthographic=true;_camera.orthographicSize=4.5f;_camera.aspect=16f/9f;_camera.clearFlags=CameraClearFlags.SolidColor;_camera.backgroundColor=new Color(.015f,.012f,.055f);_camera.transform.position=new Vector3(0,_worldY,-10);_target=new RenderTexture(640,360,16){name="BrickBreaker_640x360",filterMode=FilterMode.Bilinear};_target.Create();_camera.targetTexture=_target;
            Panel(new Vector2(6.1f,0),new Vector2(1.8f,8.2f),new Color(.06f,.08f,.2f),-2);Text("BRICK\nBREAKER",new Vector2(6.1f,3.15f),3.7f,new Color(.25f,.95f,1),out _);Text("SCORE",new Vector2(6.1f,1.75f),2.4f,Color.white,out _);Text("0",new Vector2(6.1f,1.2f),3.8f,new Color(1,.82f,.2f),out _scoreText);Text("STAGE 1",new Vector2(6.1f,.15f),2.8f,new Color(.45f,1,.75f),out _stageText);Text("LIVES 3",new Vector2(6.1f,-1f),2.8f,new Color(1,.4f,.55f),out _livesText);Text("A/D MOVE\nSPACE SERVE",new Vector2(6.1f,-2.85f),1.9f,new Color(.75f,.84f,.95f),out _);Text("",new Vector2(-.45f,0),3.6f,Color.white,out _message);_resultPanel=Panel(new Vector2(-.45f,-.2f),new Vector2(6.3f,4.05f),new Color(.01f,.015f,.06f,.95f),18);Text("",new Vector2(-.45f,-.2f),3f,Color.white,out _preview);
            _paddle=SpriteObject("Paddle",_paddleSprite,new Color(.25f,1,.85f),new Vector2(-.45f,-3.25f),7);Scale(_paddle,2.15f,.35f);_ball=SpriteObject("Ball",_ballSprite,Color.white,new Vector2(-.45f,-2.72f),8);SetHeight(_ball,.38f);BuildOverlay();_audio=Track(new GameObject("BreakoutAudio")).AddComponent<AudioSource>();}
        void PreparePreview(){ClearBricks();_paddle.SetActive(true);_ball.SetActive(true);_paddle.transform.position=ToWorld(new Vector2(-.45f,-3.25f));_ball.transform.position=ToWorld(new Vector2(-.45f,-2.72f));_scoreText.text="0";_stageText.text="ARCADE 06";_livesText.text="MEGA PACK";_message.text=string.Empty;_resultPanel.SetActive(true);_preview.gameObject.SetActive(true);ArcadeRankingBoard.ShowPreview(this,_preview,_camera,"BRICK BREAKER");}
        void DestroyTracked(GameObject g){if(g==null)return;_runtime.Remove(g);Destroy(g);}void ClearBricks(){foreach(var b in _bricks)if(b.Go!=null)DestroyTracked(b.Go);_bricks.Clear();}void HitSound(){Play(_hitClip,.28f);}void Play(AudioClip c,float v){if(c!=null)_audio.PlayOneShot(c,v);}void LoadAssets(){_paddleSprite=Resources.Load<Sprite>(Root+"Paddle");_ballSprite=Resources.Load<Sprite>(Root+"Ball");_brickSprite=Resources.Load<Sprite>(Root+"Brick");_hitClip=Resources.Load<AudioClip>(Root+"Hit");_clearClip=Resources.Load<AudioClip>(Root+"Clear");}
        void CreateScreen(){var power=GetComponent<ArcadeScreenPower>();foreach(var r in GetComponentsInChildren<MeshRenderer>(true)){var ms=r.sharedMaterials;for(int i=0;i<ms.Length;i++)if(ms[i]!=null&&power!=null&&power.IsScreenMaterial(ms[i])){_screenMaterial=new Material(ms[i]);_screenMaterial.SetTextureScale("_BaseMap",Vector2.one);_screenMaterial.SetTextureOffset("_BaseMap",Vector2.zero);ms[i]=_screenMaterial;r.sharedMaterials=ms;return;}}}
        void BuildOverlay(){var go=Track(new GameObject("@BreakoutPlayCanvas",typeof(RectTransform),typeof(Canvas),typeof(CanvasScaler),typeof(GraphicRaycaster)));_overlay=go.GetComponent<Canvas>();_overlay.renderMode=RenderMode.ScreenSpaceOverlay;_overlay.sortingOrder=32000;var sc=go.GetComponent<CanvasScaler>();sc.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;sc.referenceResolution=new Vector2(1920,1080);sc.matchWidthOrHeight=.5f;var back=new GameObject("Backdrop",typeof(RectTransform),typeof(Image));back.transform.SetParent(go.transform,false);var br=back.GetComponent<RectTransform>();br.anchorMin=Vector2.zero;br.anchorMax=Vector2.one;br.offsetMin=br.offsetMax=Vector2.zero;back.GetComponent<Image>().color=Color.black;var image=new GameObject("GameScreen",typeof(RectTransform),typeof(RawImage),typeof(AspectRatioFitter));image.transform.SetParent(go.transform,false);var rect=image.GetComponent<RectTransform>();rect.anchorMin=Vector2.zero;rect.anchorMax=Vector2.one;rect.offsetMin=rect.offsetMax=Vector2.zero;image.GetComponent<RawImage>().texture=_target;var fit=image.GetComponent<AspectRatioFitter>();fit.aspectMode=AspectRatioFitter.AspectMode.FitInParent;fit.aspectRatio=16f/9f;}
        void Show(bool p){if(_overlay!=null)_overlay.gameObject.SetActive(p);if(_screenMaterial!=null)_screenMaterial.SetTexture("_BaseMap",_target);if(_preview!=null)_preview.gameObject.SetActive(!p);if(_camera!=null){_camera.enabled=p;if(!p)_camera.Render();}}void Released(){if(!_active)return;_active=false;StopAllCoroutines();CancelInvoke();ArcadeOverlayHudSuppressor.Release();PreparePreview();Show(false);enabled=false;}
        GameObject SpriteObject(string n,Sprite s,Color c,Vector2 p,int o){var g=Track(new GameObject(n));g.transform.position=ToWorld(p);var r=g.AddComponent<SpriteRenderer>();r.sprite=s??_solid;r.color=c;r.sortingOrder=o;return g;}GameObject Panel(Vector2 p,Vector2 z,Color c,int o){var g=SpriteObject("Panel",_solid,c,p,o);g.transform.localScale=new Vector3(z.x,z.y,1);return g;}void Text(string v,Vector2 p,float s,Color c,out TextMeshPro t){var g=Track(new GameObject("Text"));g.transform.position=ToWorld(p);t=g.AddComponent<TextMeshPro>();t.text=v;t.fontSize=s;t.color=c;t.alignment=TextAlignmentOptions.Center;t.rectTransform.sizeDelta=new Vector2(7,5);t.sortingOrder=20;}Sprite Solid(){var t=new Texture2D(1,1);t.SetPixel(0,0,Color.white);t.Apply();return Sprite.Create(t,new Rect(0,0,1,1),Vector2.one*.5f,1);}static void SetHeight(GameObject g,float h){var s=g.GetComponent<SpriteRenderer>().sprite;g.transform.localScale=Vector3.one*(h/Mathf.Max(.001f,s.bounds.size.y));}static void Scale(GameObject g,float w,float h){var s=g.GetComponent<SpriteRenderer>().sprite;g.transform.localScale=new Vector3(w/Mathf.Max(.001f,s.bounds.size.x),h/Mathf.Max(.001f,s.bounds.size.y),1);}GameObject Track(GameObject g){g.transform.SetParent(null,false);_runtime.Add(g);return g;}Vector3 ToWorld(Vector2 p)=>new(p.x,_worldY+p.y,0);
        void OnDestroy(){if(_active)ArcadeOverlayHudSuppressor.Release();InteractionFocusCamera.Released-=Released;foreach(var g in _runtime)if(g!=null)Destroy(g);if(_target!=null){_target.Release();Destroy(_target);}if(_screenMaterial!=null)Destroy(_screenMaterial);}
    }
}
