// 7번 오락기에서 3×3 키 입력으로 벌레와 함정을 구분해 잡는 반응 게임을 실행한다.
using System.Collections;
using System.Collections.Generic;
using Festa.World;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Festa.Content.Arcade
{
    [DisallowMultipleComponent]
    public sealed class MegaPackBugBonkMiniGame : MonoBehaviour
    {
        const float WorldY=10700f,Duration=60f;const string Root="Arcade/MegaPackBugBonk/";
        readonly List<GameObject> _runtime=new();readonly KeyCode[] _keys={KeyCode.Q,KeyCode.W,KeyCode.E,KeyCode.A,KeyCode.S,KeyCode.D,KeyCode.Z,KeyCode.X,KeyCode.C};readonly string[] _labels={"Q","W","E","A","S","D","Z","X","C"};
        Camera _camera;RenderTexture _target;Material _screenMaterial;Sprite _solid,_bug,_gold,_bomb,_club;GameObject[] _targets=new GameObject[9],_holes=new GameObject[9];TextMeshPro _scoreText,_timeText,_comboText,_message,_preview;Canvas _overlay;AudioSource _audio;AudioClip _hit,_bonus;GameObject _resultPanel,_clubObject;
        int _activeSlot=-1,_kind,_score,_combo,_bestCombo;float _time,_nextSpawn,_hideAt,_worldY,_feverUntil;bool _active,_ended;

        void Awake(){_worldY=GetComponent<ArcadeMachineInteractable>()?.MachineId=="arcade-17"?WorldY+5000f:WorldY;LoadAssets();CreateScreen();Build();PreparePreview();Show(false);InteractionFocusCamera.Released+=Released;enabled=false;}
        public bool Begin(){if(_camera==null||_screenMaterial==null||_bug==null||_gold==null||_bomb==null)return false;ArcadeRuntimeSuspension.Resume(_runtime);ArcadeOverlayHudSuppressor.Acquire();NewGame();Show(true);_active=true;enabled=true;return true;}
        void Update(){if(!_active)return;if(!InteractionFocusCamera.IsFocused){Released();return;}if(_ended){if(ArcadeRetryInput.WasPressed())NewGame();return;}_time-=Time.deltaTime;if(_time<=0){Finish();return;}_timeText.text=Mathf.CeilToInt(_time).ToString();
            if(Time.time<_feverUntil)UpdateHud();if(_activeSlot<0&&Time.time>=_nextSpawn)Spawn();if(_activeSlot>=0&&Time.time>=_hideAt)Miss();for(int i=0;i<9;i++)if(Input.GetKeyDown(_keys[i]))Bonk(i);}
        void Spawn(){_activeSlot=Random.Range(0,9);float roll=Random.value;bool fever=Time.time<_feverUntil;_kind=fever?(roll<.45f?1:0):(roll<.13f?2:roll<.28f?1:0);var r=_targets[_activeSlot].GetComponent<SpriteRenderer>();r.sprite=_kind==2?_bomb:_kind==1?_gold:_bug;r.color=_kind==2?new Color(1,.28f,.35f):_kind==1?new Color(1,.82f,.18f):Color.white;_targets[_activeSlot].SetActive(true);float visible=Mathf.Lerp(1.05f,.48f,1f-_time/Duration)*(fever?.72f:1f);_hideAt=Time.time+visible;}
        void Bonk(int slot){if(_activeSlot<0)return;if(slot!=_activeSlot){_combo=0;UpdateHud();return;}_clubObject.transform.position=ToWorld(Cell(slot)+new Vector2(.42f,.5f));_clubObject.transform.rotation=Quaternion.Euler(0,0,-35);StartCoroutine(HideClub());if(_kind==2){_score=Mathf.Max(0,_score-500);_combo=0;Play(_hit,.45f);}else{_combo++;_bestCombo=Mathf.Max(_bestCombo,_combo);int feverMultiplier=Time.time<_feverUntil?2:1;_score+=(_kind==1?500:100)*Mathf.Clamp(1+_combo/5,1,4)*feverMultiplier;if(_combo==8){_feverUntil=Time.time+6f;_message.text="FEVER TIME!\nNO BOMBS • DOUBLE SCORE";StartCoroutine(ClearMessage());}Play(_kind==1?_bonus:_hit,_kind==1?.55f:.3f);}HideTarget();UpdateHud();}
        IEnumerator HideClub(){_clubObject.SetActive(true);yield return new WaitForSeconds(.12f);_clubObject.SetActive(false);}
        void Miss(){if(_kind!=2)_combo=0;HideTarget();UpdateHud();}
        void HideTarget(){if(_activeSlot>=0)_targets[_activeSlot].SetActive(false);_activeSlot=-1;float fever=Time.time<_feverUntil?.55f:1f;_nextSpawn=Time.time+Mathf.Lerp(.42f,.13f,1f-_time/Duration)*fever;}
        void NewGame(){StopAllCoroutines();foreach(var t in _targets)t.SetActive(false);_clubObject.SetActive(false);_activeSlot=-1;_score=_combo=_bestCombo=0;_feverUntil=0;_time=Duration;_ended=false;_nextSpawn=Time.time+.6f;_resultPanel.SetActive(false);_preview.gameObject.SetActive(false);_message.text="BONK BUGS, AVOID BOMBS!\nCOMBO 8 = FEVER TIME";UpdateHud();StartCoroutine(ClearMessage());}
        IEnumerator ClearMessage(){yield return new WaitForSeconds(1.5f);if(!_ended)_message.text=string.Empty;}
        void UpdateHud(){_scoreText.text=_score.ToString("N0");_comboText.text=Time.time<_feverUntil?$"FEVER {Mathf.Max(0,_feverUntil-Time.time):0.0}s":_combo>1?"COMBO x"+_combo:"COMBO -";}
        void Finish(){_ended=true;HideTarget();_message.text=string.Empty;_resultPanel.SetActive(true);_preview.gameObject.SetActive(true);ArcadeRankingBoard.ShowResult(this,_preview,_camera,"BUG BONK",$"TIME UP   SCORE {_score:N0}\nBEST COMBO {_bestCombo}",_score);}
        void Build(){_solid=Solid();var cg=Track(new GameObject("@BugBonkCamera"));_camera=cg.AddComponent<Camera>();_camera.orthographic=true;_camera.orthographicSize=4.5f;_camera.aspect=16f/9f;_camera.clearFlags=CameraClearFlags.SolidColor;_camera.backgroundColor=new Color(.09f,.035f,.08f);_camera.transform.position=new Vector3(0,_worldY,-10);_target=new RenderTexture(640,360,16){name="BugBonk_640x360",filterMode=FilterMode.Bilinear};_target.Create();_camera.targetTexture=_target;
            for(int i=0;i<9;i++){Vector2 p=Cell(i);_holes[i]=Panel(p,new Vector2(2.05f,1.45f),new Color(.17f,.08f,.16f),0);Panel(p+Vector2.down*.28f,new Vector2(1.25f,.35f),new Color(.015f,.01f,.025f),1);Text(_labels[i],p+new Vector2(-.72f,.45f),2.3f,new Color(.55f,.65f,.85f),out _);_targets[i]=SpriteObject("Target",_bug,Color.white,p+Vector2.up*.12f,6);SetHeight(_targets[i],1.02f);_targets[i].SetActive(false);}
            Panel(new Vector2(6.1f,0),new Vector2(1.8f,8.2f),new Color(.13f,.055f,.18f),-2);Text("BUG\nBONK",new Vector2(6.1f,3.15f),4.1f,new Color(.45f,1f,.65f),out _);Text("SCORE",new Vector2(6.1f,1.75f),2.4f,Color.white,out _);Text("0",new Vector2(6.1f,1.2f),3.8f,new Color(1,.82f,.2f),out _scoreText);Text("TIME",new Vector2(6.1f,.25f),2.4f,Color.white,out _);Text("60",new Vector2(6.1f,-.3f),3.8f,new Color(.35f,1f,.9f),out _timeText);Text("COMBO -",new Vector2(6.1f,-1.35f),2.5f,new Color(1,.45f,.7f),out _comboText);Text("QWE ASD ZXC",new Vector2(6.1f,-3.05f),1.8f,new Color(.75f,.84f,.95f),out _);Text("",new Vector2(-.55f,0),3.4f,Color.white,out _message);_resultPanel=Panel(new Vector2(-.55f,-.15f),new Vector2(6.3f,4.3f),new Color(.025f,.01f,.04f,.96f),18);Text("",new Vector2(-.55f,-.15f),2.8f,Color.white,out _preview);_clubObject=SpriteObject("Club",_club,Color.white,Vector2.zero,10);SetHeight(_clubObject,1.25f);_clubObject.SetActive(false);BuildOverlay();_audio=Track(new GameObject("BugBonkAudio")).AddComponent<AudioSource>();}
        static Vector2 Cell(int i)=>new(-3.75f+(i%3)*3.2f,2.35f-(i/3)*2.25f);
        void PreparePreview(){foreach(var t in _targets)t.SetActive(false);_targets[0].SetActive(true);_targets[4].SetActive(true);_targets[8].SetActive(true);_scoreText.text="0";_timeText.text="60";_comboText.text="ARCADE 07";_message.text=string.Empty;_resultPanel.SetActive(true);_preview.gameObject.SetActive(true);ArcadeRankingBoard.ShowPreview(this,_preview,_camera,"BUG BONK");}
        void LoadAssets(){_bug=Resources.Load<Sprite>(Root+"Bug");_gold=Resources.Load<Sprite>(Root+"GoldenBug");_bomb=Resources.Load<Sprite>(Root+"Bomb");_club=Resources.Load<Sprite>(Root+"Club");_hit=Resources.Load<AudioClip>(Root+"Hit");_bonus=Resources.Load<AudioClip>(Root+"Bonus");}void Play(AudioClip c,float v){if(c!=null)_audio.PlayOneShot(c,v);}
        void CreateScreen(){var power=GetComponent<ArcadeScreenPower>();foreach(var r in GetComponentsInChildren<MeshRenderer>(true)){var ms=r.sharedMaterials;for(int i=0;i<ms.Length;i++)if(ms[i]!=null&&power!=null&&power.IsScreenMaterial(ms[i])){_screenMaterial=new Material(ms[i]);_screenMaterial.SetTextureScale("_BaseMap",Vector2.one);_screenMaterial.SetTextureOffset("_BaseMap",Vector2.zero);ms[i]=_screenMaterial;r.sharedMaterials=ms;return;}}}
        void BuildOverlay(){var go=Track(new GameObject("@BugBonkPlayCanvas",typeof(RectTransform),typeof(Canvas),typeof(CanvasScaler),typeof(GraphicRaycaster)));_overlay=go.GetComponent<Canvas>();_overlay.renderMode=RenderMode.ScreenSpaceOverlay;_overlay.sortingOrder=32000;var sc=go.GetComponent<CanvasScaler>();sc.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;sc.referenceResolution=new Vector2(1920,1080);sc.matchWidthOrHeight=.5f;var back=new GameObject("Backdrop",typeof(RectTransform),typeof(Image));back.transform.SetParent(go.transform,false);var br=back.GetComponent<RectTransform>();br.anchorMin=Vector2.zero;br.anchorMax=Vector2.one;br.offsetMin=br.offsetMax=Vector2.zero;back.GetComponent<Image>().color=Color.black;var image=new GameObject("GameScreen",typeof(RectTransform),typeof(RawImage),typeof(AspectRatioFitter));image.transform.SetParent(go.transform,false);var rect=image.GetComponent<RectTransform>();rect.anchorMin=Vector2.zero;rect.anchorMax=Vector2.one;rect.offsetMin=rect.offsetMax=Vector2.zero;image.GetComponent<RawImage>().texture=_target;var fit=image.GetComponent<AspectRatioFitter>();fit.aspectMode=AspectRatioFitter.AspectMode.FitInParent;fit.aspectRatio=16f/9f;}
        void Show(bool p){if(_overlay!=null)_overlay.gameObject.SetActive(p);if(_screenMaterial!=null)_screenMaterial.SetTexture("_BaseMap",_target);if(_preview!=null)_preview.gameObject.SetActive(!p);if(_camera!=null){_camera.enabled=p;if(!p)_camera.Render();}if(!p)ArcadeRuntimeSuspension.Suspend(_runtime);}void Released(){if(!_active)return;_active=false;StopAllCoroutines();CancelInvoke();ArcadeOverlayHudSuppressor.Release();PreparePreview();Show(false);enabled=false;}
        GameObject SpriteObject(string n,Sprite s,Color c,Vector2 p,int o){var g=Track(new GameObject(n));g.transform.position=ToWorld(p);var r=g.AddComponent<SpriteRenderer>();r.sprite=s??_solid;r.color=c;r.sortingOrder=o;return g;}GameObject Panel(Vector2 p,Vector2 z,Color c,int o){var g=SpriteObject("Panel",_solid,c,p,o);g.transform.localScale=new Vector3(z.x,z.y,1);return g;}void Text(string v,Vector2 p,float s,Color c,out TextMeshPro t){var g=Track(new GameObject("Text"));g.transform.position=ToWorld(p);t=g.AddComponent<TextMeshPro>();t.text=v;t.fontSize=s;t.color=c;t.alignment=TextAlignmentOptions.Center;t.rectTransform.sizeDelta=new Vector2(7,5);t.sortingOrder=20;}Sprite Solid(){var t=new Texture2D(1,1);t.SetPixel(0,0,Color.white);t.Apply();return Sprite.Create(t,new Rect(0,0,1,1),Vector2.one*.5f,1);}static void SetHeight(GameObject g,float h){var s=g.GetComponent<SpriteRenderer>().sprite;g.transform.localScale=Vector3.one*(h/Mathf.Max(.001f,s.bounds.size.y));}GameObject Track(GameObject g){g.transform.SetParent(null,false);_runtime.Add(g);return g;}Vector3 ToWorld(Vector2 p)=>new(p.x,_worldY+p.y,0);
        void OnDestroy(){if(_active)ArcadeOverlayHudSuppressor.Release();InteractionFocusCamera.Released-=Released;foreach(var g in _runtime)if(g!=null)Destroy(g);if(_target!=null){_target.Release();Destroy(_target);}if(_screenMaterial!=null)Destroy(_screenMaterial);}
    }
}
