// 9·19번 오락기에서 먹이를 모으며 길어지는 클래식 네온 스네이크 게임을 실행한다.
using System.Collections.Generic;
using Festa.World;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Festa.Content.Arcade
{
    [DisallowMultipleComponent]
    public sealed class MegaPackNeonSnakeMiniGame : MonoBehaviour
    {
        const float BaseWorldY=10900f,Duration=75f,Cell=.52f;const int W=19,H=13;const string Root="Arcade/MegaPackNeonSnake/";
        readonly List<GameObject> _runtime=new(),_segments=new();readonly List<Vector2Int> _body=new();
        Camera _camera;RenderTexture _target;Material _screenMaterial;Sprite _solid,_foodSprite;AudioClip _hit,_bonus;AudioSource _audio;Canvas _overlay;GameObject _food,_resultPanel;TextMeshPro _scoreText,_timeText,_lengthText,_message,_preview;
        Vector2Int _dir=Vector2Int.right,_queued=Vector2Int.right,_foodCell;float _time,_stepAt,_worldY,_foodExpiresAt;int _score,_eaten,_goldEaten;bool _active,_ended,_goldFood;
        Vector2 Origin=>new(-5.45f,-3.1f);

        void Awake(){_worldY=GetComponent<ArcadeMachineInteractable>()?.MachineId=="arcade-19"?BaseWorldY+5000f:BaseWorldY;LoadAssets();CreateScreen();Build();PreparePreview();Show(false);InteractionFocusCamera.Released+=Released;enabled=false;}
        public bool Begin(){if(_camera==null||_screenMaterial==null||_foodSprite==null)return false;ArcadeRuntimeSuspension.Resume(_runtime);ArcadeOverlayHudSuppressor.Acquire();enabled=true;NewGame();Show(true);_active=true;return true;}
        void Update(){if(!_active)return;if(!InteractionFocusCamera.IsFocused){Released();return;}if(_ended){if(ArcadeRetryInput.WasPressed())NewGame();return;}_time-=Time.deltaTime;if(_time<=0){Finish("TIME UP");return;}if(_goldFood&&Time.time>=_foodExpiresAt)PlaceFood();ReadInput();if(Time.time>=_stepAt)Step();UpdateHud();}
        void ReadInput(){Vector2Int n=_queued;if(Input.GetKeyDown(KeyCode.W)||Input.GetKeyDown(KeyCode.UpArrow))n=Vector2Int.up;else if(Input.GetKeyDown(KeyCode.S)||Input.GetKeyDown(KeyCode.DownArrow))n=Vector2Int.down;else if(Input.GetKeyDown(KeyCode.A)||Input.GetKeyDown(KeyCode.LeftArrow))n=Vector2Int.left;else if(Input.GetKeyDown(KeyCode.D)||Input.GetKeyDown(KeyCode.RightArrow))n=Vector2Int.right;if(n+_dir!=Vector2Int.zero)_queued=n;}
        void Step(){_dir=_queued;var head=_body[0]+_dir;head=new Vector2Int((head.x+W)%W,(head.y+H)%H);if(_body.Contains(head)){Play(_hit,.5f);Finish("CRASH!");return;}bool ate=head==_foodCell,ateGold=ate&&_goldFood;_body.Insert(0,head);if(ate){_eaten++;if(ateGold){_goldEaten++;_score+=1200+_body.Count*20;_time=Mathf.Min(90f,_time+5f);for(int i=0;i<2&&_body.Count>3;i++)_body.RemoveAt(_body.Count-1);_message.text="GOLD FOOD! +5s\nTAIL CUT -2";Invoke(nameof(ClearMessage),.75f);}else _score+=250+_body.Count*12;Play(_bonus,ateGold?.65f:.5f);PlaceFood();}else _body.RemoveAt(_body.Count-1);SyncBody();_stepAt=Time.time+Mathf.Lerp(.16f,.075f,Mathf.Clamp01(_eaten/22f));}
        void NewGame(){CancelInvoke();ClearBody();_body.Add(new Vector2Int(6,6));_body.Add(new Vector2Int(5,6));_body.Add(new Vector2Int(4,6));_dir=_queued=Vector2Int.right;_score=_eaten=_goldEaten=0;_time=Duration;_ended=false;_resultPanel.SetActive(false);_preview.gameObject.SetActive(false);_message.text="EAT • GROW • SURVIVE\nGOLD FOOD CUTS YOUR TAIL";Invoke(nameof(ClearMessage),1.4f);PlaceFood();SyncBody();_stepAt=Time.time+.5f;UpdateHud();}
        void PlaceFood(){_food.SetActive(true);_goldFood=Random.value<.22f;_foodExpiresAt=Time.time+4.5f;do _foodCell=new Vector2Int(Random.Range(0,W),Random.Range(0,H));while(_body.Contains(_foodCell));_food.transform.position=ToWorld(Grid(_foodCell));_food.GetComponent<SpriteRenderer>().color=_goldFood?new Color(1f,.78f,.12f):Color.white;}
        void SyncBody(){while(_segments.Count<_body.Count){var g=Panel(Vector2.zero,new Vector2(Cell*.86f,Cell*.86f),new Color(.2f,1f,.75f),8);_segments.Add(g);}for(int i=0;i<_segments.Count;i++){bool on=i<_body.Count;_segments[i].SetActive(on);if(on){_segments[i].transform.position=ToWorld(Grid(_body[i]));_segments[i].GetComponent<SpriteRenderer>().color=i==0?new Color(.95f,1f,.3f):Color.Lerp(new Color(.1f,.95f,.85f),new Color(.35f,.25f,1f),i/(float)Mathf.Max(1,_body.Count-1));}}}
        void DestroyTracked(GameObject g){if(g==null)return;_runtime.Remove(g);Destroy(g);}void ClearBody(){foreach(var g in _segments)if(g!=null)DestroyTracked(g);_segments.Clear();_body.Clear();}
        void ClearMessage(){if(!_ended)_message.text=string.Empty;}void UpdateHud(){_scoreText.text=_score.ToString("N0");_timeText.text=Mathf.CeilToInt(_time).ToString();_lengthText.text=$"LENGTH {_body.Count}\nFOOD {_eaten} • GOLD {_goldEaten}";}
        void Finish(string title){CancelInvoke();_ended=true;_message.text=string.Empty;_resultPanel.SetActive(true);_preview.gameObject.SetActive(true);ArcadeRankingBoard.ShowResult(this,_preview,_camera,"NEON SNAKE",$"{title}   SCORE {_score:N0}\nLENGTH {_body.Count}   GOLD {_goldEaten}",_score);}
        void Build(){_solid=Solid();var cg=Track(new GameObject("@NeonSnakeCamera"));_camera=cg.AddComponent<Camera>();_camera.orthographic=true;_camera.orthographicSize=4.5f;_camera.aspect=16f/9f;_camera.clearFlags=CameraClearFlags.SolidColor;_camera.backgroundColor=new Color(.015f,.025f,.055f);_camera.transform.position=new Vector3(0,_worldY,-10);_target=new RenderTexture(640,360,16){name="NeonSnake_640x360",filterMode=FilterMode.Bilinear};_target.Create();_camera.targetTexture=_target;
            Panel(new Vector2(-.75f,.02f),new Vector2(W*Cell+.3f,H*Cell+.3f),new Color(.025f,.07f,.105f),0);for(int x=0;x<=W;x++)Panel(Origin+new Vector2(x*Cell-.26f,H*Cell*.5f-.26f),new Vector2(.018f,H*Cell),new Color(.08f,.22f,.28f,.5f),1);for(int y=0;y<=H;y++)Panel(Origin+new Vector2(W*Cell*.5f-.26f,y*Cell-.26f),new Vector2(W*Cell,.018f),new Color(.08f,.22f,.28f,.5f),1);
            _food=SpriteObject("Food",_foodSprite,Color.white,Vector2.zero,9);SetHeight(_food,.48f);Panel(new Vector2(6.15f,0),new Vector2(1.75f,8.2f),new Color(.035f,.11f,.16f),3);Text("NEON\nSNAKE",new Vector2(6.15f,3.1f),3.7f,new Color(.35f,1f,.7f),out _);Text("SCORE",new Vector2(6.15f,1.65f),2.2f,Color.white,out _);Text("0",new Vector2(6.15f,1.12f),3.5f,new Color(1,.82f,.2f),out _scoreText);Text("TIME",new Vector2(6.15f,.25f),2.2f,Color.white,out _);Text("75",new Vector2(6.15f,-.28f),3.5f,new Color(.3f,1f,.85f),out _timeText);Text("LENGTH 3\nFOOD 0",new Vector2(6.15f,-1.5f),2.15f,Color.white,out _lengthText);Text("WASD\nARROWS",new Vector2(6.15f,-3f),1.8f,new Color(.72f,.82f,1),out _);Text("",new Vector2(-.75f,0),2.55f,Color.white,out _message);_resultPanel=Panel(new Vector2(-.75f,-.05f),new Vector2(7.1f,5.4f),new Color(.01f,.025f,.06f,.97f),18);Text("",new Vector2(-.75f,-.05f),2.05f,Color.white,out _preview);BuildOverlay();_audio=Track(new GameObject("SnakeAudio")).AddComponent<AudioSource>();}
        Vector2 Grid(Vector2Int p)=>Origin+new Vector2(p.x*Cell,p.y*Cell);void PreparePreview(){ClearBody();_food.SetActive(false);_scoreText.text="0";_timeText.text="75";_lengthText.text="ARCADE 09 / 19";_message.text=string.Empty;_resultPanel.SetActive(true);_preview.gameObject.SetActive(true);ArcadeRankingBoard.ShowPreview(this,_preview,_camera,"NEON SNAKE\nEAT • GROW • SURVIVE");}
        void LoadAssets(){_foodSprite=Resources.Load<Sprite>(Root+"Food");_hit=Resources.Load<AudioClip>(Root+"Hit");_bonus=Resources.Load<AudioClip>(Root+"Bonus");}void Play(AudioClip c,float v){if(c!=null)_audio.PlayOneShot(c,v);}
        void CreateScreen(){var power=GetComponent<ArcadeScreenPower>();foreach(var r in GetComponentsInChildren<MeshRenderer>(true)){var ms=r.sharedMaterials;for(int i=0;i<ms.Length;i++)if(ms[i]!=null&&power!=null&&power.IsScreenMaterial(ms[i])){_screenMaterial=new Material(ms[i]);_screenMaterial.SetTextureScale("_BaseMap",Vector2.one);_screenMaterial.SetTextureOffset("_BaseMap",Vector2.zero);ms[i]=_screenMaterial;r.sharedMaterials=ms;return;}}}
        void BuildOverlay(){var go=Track(new GameObject("@NeonSnakePlayCanvas",typeof(RectTransform),typeof(Canvas),typeof(CanvasScaler),typeof(GraphicRaycaster)));_overlay=go.GetComponent<Canvas>();_overlay.renderMode=RenderMode.ScreenSpaceOverlay;_overlay.sortingOrder=32000;var sc=go.GetComponent<CanvasScaler>();sc.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;sc.referenceResolution=new Vector2(1920,1080);sc.matchWidthOrHeight=.5f;var back=new GameObject("Backdrop",typeof(RectTransform),typeof(Image));back.transform.SetParent(go.transform,false);var br=back.GetComponent<RectTransform>();br.anchorMin=Vector2.zero;br.anchorMax=Vector2.one;br.offsetMin=br.offsetMax=Vector2.zero;back.GetComponent<Image>().color=Color.black;var image=new GameObject("GameScreen",typeof(RectTransform),typeof(RawImage),typeof(AspectRatioFitter));image.transform.SetParent(go.transform,false);var rect=image.GetComponent<RectTransform>();rect.anchorMin=Vector2.zero;rect.anchorMax=Vector2.one;rect.offsetMin=rect.offsetMax=Vector2.zero;image.GetComponent<RawImage>().texture=_target;var fit=image.GetComponent<AspectRatioFitter>();fit.aspectMode=AspectRatioFitter.AspectMode.FitInParent;fit.aspectRatio=16f/9f;}
        void Show(bool p){if(_overlay!=null)_overlay.gameObject.SetActive(p);if(_screenMaterial!=null)_screenMaterial.SetTexture("_BaseMap",_target);if(_preview!=null)_preview.gameObject.SetActive(!p);if(_camera!=null){_camera.enabled=p;if(!p)_camera.Render();}if(!p)ArcadeRuntimeSuspension.Suspend(_runtime);}void Released(){if(!_active)return;_active=false;StopAllCoroutines();CancelInvoke();ArcadeOverlayHudSuppressor.Release();if(_food!=null&&_preview!=null){PreparePreview();Show(false);}enabled=false;}
        GameObject SpriteObject(string n,Sprite s,Color c,Vector2 p,int o){var g=Track(new GameObject(n));g.transform.position=ToWorld(p);var r=g.AddComponent<SpriteRenderer>();r.sprite=s??_solid;r.color=c;r.sortingOrder=o;return g;}GameObject Panel(Vector2 p,Vector2 z,Color c,int o){var g=SpriteObject("Panel",_solid,c,p,o);g.transform.localScale=new Vector3(z.x,z.y,1);return g;}void Text(string v,Vector2 p,float s,Color c,out TextMeshPro t){var g=Track(new GameObject("Text"));g.transform.position=ToWorld(p);t=g.AddComponent<TextMeshPro>();t.text=v;t.fontSize=s;t.color=c;t.alignment=TextAlignmentOptions.Center;t.rectTransform.sizeDelta=new Vector2(8,5);t.sortingOrder=20;}Sprite Solid(){var t=new Texture2D(1,1);t.SetPixel(0,0,Color.white);t.Apply();return Sprite.Create(t,new Rect(0,0,1,1),Vector2.one*.5f,1);}static void SetHeight(GameObject g,float h){var s=g.GetComponent<SpriteRenderer>().sprite;g.transform.localScale=Vector3.one*(h/Mathf.Max(.001f,s.bounds.size.y));}GameObject Track(GameObject g){g.transform.SetParent(null,false);_runtime.Add(g);return g;}Vector3 ToWorld(Vector2 p)=>new(p.x,_worldY+p.y,0);
        void OnDestroy(){if(_active)ArcadeOverlayHudSuppressor.Release();InteractionFocusCamera.Released-=Released;ClearBody();foreach(var g in _runtime)if(g!=null)Destroy(g);if(_target!=null){_target.Release();Destroy(_target);}if(_screenMaterial!=null)Destroy(_screenMaterial);}
    }
}
