// 5번 오락기에서 차량을 피하고 통나무를 타고 강을 건너는 횡단 게임을 실행한다.
using System.Collections;
using System.Collections.Generic;
using Festa.World;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Festa.Content.Arcade
{
    [DisallowMultipleComponent]
    public sealed class MegaPackCrossyMiniGame : MonoBehaviour
    {
        const float WorldY=10500f;const string Root="Arcade/MegaPackCrossy/";
        sealed class Mover{public GameObject Go;public Vector2 Pos;public float Speed;public float SafeHalfWidth;public bool Log;}
        readonly List<GameObject> _runtime=new();readonly List<Mover> _movers=new();Camera _camera;RenderTexture _target;Material _screenMaterial;Sprite _solid,_playerSprite,_carSprite,_logSprite;GameObject _player,_resultPanel;
        TextMeshPro _scoreText,_livesText,_timeText,_message,_preview;Canvas _overlay;AudioSource _audio;AudioClip _goalClip,_hitClip;Vector2 _playerPos,_playerTarget,_hopFrom;int _score,_lives,_crossings,_forwardChain,_bestChain;float _time,_nextMove,_safeUntil,_hopStarted,_worldY,_lastForwardAt;bool _active,_ended,_moving;

        void Awake(){_worldY=GetComponent<ArcadeMachineInteractable>()?.MachineId=="arcade-15"?WorldY+5000f:WorldY;LoadAssets();CreateScreen();Build();PreparePreview();Show(false);InteractionFocusCamera.Released+=Released;enabled=false;}
        public bool Begin(){if(_camera==null||_screenMaterial==null||_playerSprite==null||_carSprite==null||_logSprite==null)return false;ArcadeRuntimeSuspension.Resume(_runtime);ArcadeOverlayHudSuppressor.Acquire();NewGame();Show(true);_active=true;enabled=true;return true;}
        void Update(){if(!_active)return;if(!InteractionFocusCamera.IsFocused){Released();return;}if(_ended){if(ArcadeRetryInput.WasPressed())NewGame();return;}_time-=Time.deltaTime;if(_time<=0){Finish();return;}_timeText.text=Mathf.CeilToInt(_time).ToString();
            if(!_moving&&Time.time>=_nextMove){Vector2 step=Vector2.zero;if(Input.GetKeyDown(KeyCode.UpArrow)||Input.GetKeyDown(KeyCode.W))step.y=1;if(Input.GetKeyDown(KeyCode.DownArrow)||Input.GetKeyDown(KeyCode.S))step.y=-1;if(Input.GetKeyDown(KeyCode.LeftArrow)||Input.GetKeyDown(KeyCode.A))step.x=-1;if(Input.GetKeyDown(KeyCode.RightArrow)||Input.GetKeyDown(KeyCode.D))step.x=1;if(step!=Vector2.zero){if(step.y>0){_forwardChain=Time.time-_lastForwardAt<.9f?_forwardChain+1:1;_lastForwardAt=Time.time;_bestChain=Mathf.Max(_bestChain,_forwardChain);_score+=25*Mathf.Min(_forwardChain,10);_scoreText.text=_score.ToString("N0");}else if(step.y<0)_forwardChain=0;_hopFrom=_playerPos;_playerTarget=_playerPos+step*1.05f;_playerTarget.x=Mathf.Clamp(_playerTarget.x,-5.15f,5.15f);_playerTarget.y=Mathf.Clamp(_playerTarget.y,-3.45f,3.55f);_hopStarted=Time.time;_moving=true;_nextMove=Time.time+.08f;}}
            if(_moving){float t=Mathf.Clamp01((Time.time-_hopStarted)/.18f);_playerPos=Vector2.Lerp(_hopFrom,_playerTarget,Mathf.SmoothStep(0,1,t));float hop=Mathf.Sin(t*Mathf.PI)*.28f;_player.transform.position=ToWorld(_playerPos+Vector2.up*hop);if(t>=1f){_playerPos=_playerTarget;_moving=false;}}
            MoveTraffic();CheckHazards();if(!_moving)_player.transform.position=ToWorld(_playerPos);_player.GetComponent<SpriteRenderer>().color=Time.time<_safeUntil&&Mathf.FloorToInt(Time.time*10)%2==0?new Color(1,1,1,.35f):Color.white;if(!_moving&&_playerPos.y>3.35f)ReachGoal();}
        void MoveTraffic(){foreach(var m in _movers){m.Pos.x+=m.Speed*Time.deltaTime;if(m.Pos.x>6.5f)m.Pos.x=-6.5f;if(m.Pos.x< -6.5f)m.Pos.x=6.5f;m.Go.transform.position=ToWorld(m.Pos);}}
        void CheckHazards(){if(Time.time<_safeUntil||_moving)return;bool river=_playerPos.y>.65f&&_playerPos.y<2.15f;Mover support=null;foreach(var m in _movers){if(Mathf.Abs(m.Pos.y-_playerPos.y)>.18f)continue;float hit=Mathf.Abs(m.Pos.x-_playerPos.x);if(m.Log&&hit<=m.SafeHalfWidth)support=m;if(!m.Log&&hit<.62f){Hit();return;}}if(river){if(support==null){Hit();return;}float drift=support.Speed*Time.deltaTime;_playerPos.x+=drift;_playerTarget.x+=drift;if(Mathf.Abs(_playerPos.x)>5.25f)Hit();}}
        void ReachGoal(){_crossings++;_score+=1000+Mathf.CeilToInt(_time)*20+_forwardChain*100;_time=Mathf.Min(90f,_time+4f);_message.text=$"FAST CROSS x{Mathf.Max(1,_forwardChain)}! +4s";StartCoroutine(ClearMessage());_scoreText.text=_score.ToString("N0");Play(_goalClip,.5f);ResetPlayer();if(_crossings>=5)Finish();}
        void Hit(){_lives--;_forwardChain=0;_livesText.text="LIVES "+_lives;Play(_hitClip,.5f);if(_lives<=0){Finish();return;}ResetPlayer();_safeUntil=Time.time+2f;}
        void ResetPlayer(){_playerPos=new Vector2(0,-3.35f);_playerTarget=_playerPos;_moving=false;_player.transform.position=ToWorld(_playerPos);}
        void NewGame(){StopAllCoroutines();_score=0;_lives=3;_crossings=_forwardChain=_bestChain=0;_lastForwardAt=-99f;_time=75;_ended=false;_scoreText.text="0";_livesText.text="LIVES 3";_timeText.text="75";_resultPanel.SetActive(false);_preview.gameObject.SetActive(false);_message.text="CROSS THE ROAD & RIVER\nQUICK FORWARD HOPS BUILD RUSH\n5 CROSSINGS TO WIN";ResetPlayer();_safeUntil=Time.time+2.5f;StartCoroutine(ClearMessage());}
        IEnumerator ClearMessage(){yield return new WaitForSeconds(1.6f);if(!_ended)_message.text=string.Empty;}
        void Finish(){_ended=true;_player.SetActive(false);_message.text=string.Empty;_resultPanel.SetActive(true);_preview.gameObject.SetActive(true);ArcadeRankingBoard.ShowResult(this,_preview,_camera,"CROSSY PICKLE",$"{(_crossings>=5?"YOU MADE IT!":"GAME OVER")}   SCORE {_score:N0}\nBEST FORWARD RUSH x{_bestChain}",_score);}
        void Build(){_solid=Solid();var cg=Track(new GameObject("@CrossyCamera"));_camera=cg.AddComponent<Camera>();_camera.orthographic=true;_camera.orthographicSize=4.5f;_camera.aspect=16f/9f;_camera.clearFlags=CameraClearFlags.SolidColor;_camera.backgroundColor=new Color(.07f,.18f,.1f);_camera.transform.position=new Vector3(0,_worldY,-10);_target=new RenderTexture(640,360,16){name="CrossyPickle_640x360",filterMode=FilterMode.Bilinear};_target.Create();_camera.targetTexture=_target;
            Panel(new Vector2(-.5f,-1.25f),new Vector2(12.2f,2.1f),new Color(.11f,.12f,.15f),-4);for(int i=-5;i<=4;i++)Panel(new Vector2(i*1.2f,-1.25f),new Vector2(.62f,.08f),new Color(1f,.85f,.22f),-3);Panel(new Vector2(-.5f,1.8f),new Vector2(12.2f,2.15f),new Color(.02f,.25f,.48f),-4);Panel(new Vector2(-.5f,3.4f),new Vector2(12.2f,.65f),new Color(.2f,.65f,.24f),-4);Panel(new Vector2(-.5f,-3.45f),new Vector2(12.2f,.65f),new Color(.2f,.65f,.24f),-4);
            AddMover(_carSprite,new Vector2(-4.5f,-2.30f),2.7f,false,new Color(1f,.3f,.25f),.82f);AddMover(_carSprite,new Vector2(1.7f,-2.30f),2.7f,false,new Color(1f,.65f,.15f),.82f);AddMover(_carSprite,new Vector2(4.4f,-.20f),-3.15f,false,new Color(.45f,.8f,1f),.82f);AddMover(_carSprite,new Vector2(-1.4f,-.20f),-3.15f,false,new Color(.8f,.35f,1f),.82f);
            AddMover(_logSprite,new Vector2(-4f,.85f),1.35f,true,Color.white,.48f);AddMover(_logSprite,new Vector2(0f,.85f),1.35f,true,Color.white,.48f);AddMover(_logSprite,new Vector2(4f,.85f),1.35f,true,Color.white,.48f);AddMover(_logSprite,new Vector2(-2f,1.90f),-1.65f,true,new Color(.9f,.78f,.58f),.48f);AddMover(_logSprite,new Vector2(3f,1.90f),-1.65f,true,new Color(.9f,.78f,.58f),.48f);
            Panel(new Vector2(6.15f,0),new Vector2(1.7f,8.2f),new Color(.05f,.12f,.16f),-2);Text("CROSSY\nPICKLE",new Vector2(6.15f,3.15f),3.8f,new Color(.45f,1f,.55f),out _);Text("SCORE",new Vector2(6.15f,1.75f),2.4f,Color.white,out _);Text("0",new Vector2(6.15f,1.2f),3.8f,new Color(1,.82f,.2f),out _scoreText);Text("TIME",new Vector2(6.15f,.2f),2.3f,Color.white,out _);Text("75",new Vector2(6.15f,-.35f),3.7f,new Color(.35f,1f,.9f),out _timeText);Text("LIVES 3",new Vector2(6.15f,-1.35f),2.7f,new Color(1,.45f,.55f),out _livesText);Text("ARROWS MOVE",new Vector2(6.15f,-3.05f),1.9f,new Color(.75f,.85f,.95f),out _);Text("",new Vector2(-.5f,0),3.4f,Color.white,out _message);_resultPanel=Panel(new Vector2(-.5f,-.15f),new Vector2(6.2f,4f),new Color(.01f,.025f,.04f,.94f),18);Text("",new Vector2(-.5f,-.15f),3f,Color.white,out _preview);_player=SpriteObject("Pickle",_playerSprite,Color.white,new Vector2(0,-3.35f),8);SetHeight(_player,.88f);BuildOverlay();_audio=Track(new GameObject("CrossyAudio")).AddComponent<AudioSource>();}
        void AddMover(Sprite s,Vector2 p,float speed,bool log,Color c,float h){var g=SpriteObject(log?"Log":"Car",s,c,p,5);SetHeight(g,h);if(log)g.transform.localScale=new Vector3(g.transform.localScale.x*2.1f,g.transform.localScale.y,1);float visibleHalf=g.GetComponent<SpriteRenderer>().bounds.size.x*.5f;float safeHalf=log?Mathf.Max(.55f,visibleHalf-.16f):.62f;_movers.Add(new Mover{Go=g,Pos=p,Speed=speed,Log=log,SafeHalfWidth=safeHalf});}
        void PreparePreview(){_player.SetActive(true);ResetPlayer();_scoreText.text="0";_timeText.text="75";_livesText.text="ARCADE 05";_message.text=string.Empty;_resultPanel.SetActive(true);_preview.gameObject.SetActive(true);ArcadeRankingBoard.ShowPreview(this,_preview,_camera,"CROSSY PICKLE");}
        void LoadAssets(){_playerSprite=Resources.Load<Sprite>(Root+"Player");_carSprite=Resources.Load<Sprite>(Root+"Car");_logSprite=Resources.Load<Sprite>(Root+"RiverLog")??Resources.Load<Sprite>(Root+"Log");_goalClip=Resources.Load<AudioClip>(Root+"Goal");_hitClip=Resources.Load<AudioClip>(Root+"Hit");}void Play(AudioClip c,float v){if(c!=null)_audio.PlayOneShot(c,v);}
        void CreateScreen(){var power=GetComponent<ArcadeScreenPower>();foreach(var r in GetComponentsInChildren<MeshRenderer>(true)){var ms=r.sharedMaterials;for(int i=0;i<ms.Length;i++)if(ms[i]!=null&&power!=null&&power.IsScreenMaterial(ms[i])){_screenMaterial=new Material(ms[i]);_screenMaterial.SetTextureScale("_BaseMap",Vector2.one);_screenMaterial.SetTextureOffset("_BaseMap",Vector2.zero);ms[i]=_screenMaterial;r.sharedMaterials=ms;return;}}}
        void BuildOverlay(){var go=Track(new GameObject("@CrossyPlayCanvas",typeof(RectTransform),typeof(Canvas),typeof(CanvasScaler),typeof(GraphicRaycaster)));_overlay=go.GetComponent<Canvas>();_overlay.renderMode=RenderMode.ScreenSpaceOverlay;_overlay.sortingOrder=32000;var sc=go.GetComponent<CanvasScaler>();sc.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;sc.referenceResolution=new Vector2(1920,1080);sc.matchWidthOrHeight=.5f;var back=new GameObject("Backdrop",typeof(RectTransform),typeof(Image));back.transform.SetParent(go.transform,false);var br=back.GetComponent<RectTransform>();br.anchorMin=Vector2.zero;br.anchorMax=Vector2.one;br.offsetMin=br.offsetMax=Vector2.zero;back.GetComponent<Image>().color=Color.black;var image=new GameObject("GameScreen",typeof(RectTransform),typeof(RawImage),typeof(AspectRatioFitter));image.transform.SetParent(go.transform,false);var rect=image.GetComponent<RectTransform>();rect.anchorMin=Vector2.zero;rect.anchorMax=Vector2.one;rect.offsetMin=rect.offsetMax=Vector2.zero;image.GetComponent<RawImage>().texture=_target;var fit=image.GetComponent<AspectRatioFitter>();fit.aspectMode=AspectRatioFitter.AspectMode.FitInParent;fit.aspectRatio=16f/9f;}
        void Show(bool p){if(_overlay!=null)_overlay.gameObject.SetActive(p);if(_screenMaterial!=null)_screenMaterial.SetTexture("_BaseMap",_target);if(_preview!=null)_preview.gameObject.SetActive(!p);if(_camera!=null){_camera.enabled=p;if(!p)_camera.Render();}if(!p)ArcadeRuntimeSuspension.Suspend(_runtime);}void Released(){if(!_active)return;_active=false;StopAllCoroutines();CancelInvoke();ArcadeOverlayHudSuppressor.Release();PreparePreview();Show(false);enabled=false;}
        GameObject SpriteObject(string n,Sprite s,Color c,Vector2 p,int o){var g=Track(new GameObject(n));g.transform.position=ToWorld(p);var r=g.AddComponent<SpriteRenderer>();r.sprite=s??_solid;r.color=c;r.sortingOrder=o;return g;}GameObject Panel(Vector2 p,Vector2 z,Color c,int o){var g=SpriteObject("Panel",_solid,c,p,o);g.transform.localScale=new Vector3(z.x,z.y,1);return g;}void Text(string v,Vector2 p,float s,Color c,out TextMeshPro t){var g=Track(new GameObject("Text"));g.transform.position=ToWorld(p);t=g.AddComponent<TextMeshPro>();t.text=v;t.fontSize=s;t.color=c;t.alignment=TextAlignmentOptions.Center;t.rectTransform.sizeDelta=new Vector2(7,5);t.sortingOrder=20;}Sprite Solid(){var t=new Texture2D(1,1);t.SetPixel(0,0,Color.white);t.Apply();return Sprite.Create(t,new Rect(0,0,1,1),Vector2.one*.5f,1);}static void SetHeight(GameObject g,float h){var s=g.GetComponent<SpriteRenderer>().sprite;g.transform.localScale=Vector3.one*(h/Mathf.Max(.001f,s.bounds.size.y));}GameObject Track(GameObject g){g.transform.SetParent(null,false);_runtime.Add(g);return g;}Vector3 ToWorld(Vector2 p)=>new(p.x,_worldY+p.y,0);
        void OnDestroy(){if(_active)ArcadeOverlayHudSuppressor.Release();InteractionFocusCamera.Released-=Released;foreach(var g in _runtime)if(g!=null)Destroy(g);if(_target!=null){_target.Release();Destroy(_target);}if(_screenMaterial!=null)Destroy(_screenMaterial);}
    }
}
