// 4번 오락기에서 코인을 모으고 순찰 적을 피하는 탑다운 미로 게임을 실행한다.
using System.Collections;
using System.Collections.Generic;
using Festa.World;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Festa.Content.Arcade
{
    [DisallowMultipleComponent]
    public sealed class MegaPackMazeMiniGame : MonoBehaviour
    {
        const float WorldY=10400f; const string Root="Arcade/MegaPackMaze/";
        readonly List<GameObject> _runtime=new(); readonly List<GameObject> _coins=new(); readonly List<Rect> _walls=new(); readonly List<Enemy> _enemies=new();
        sealed class Enemy { public GameObject Go; public Vector2 Pos, Velocity; }
        Camera _camera;RenderTexture _target;Material _screenMaterial;Sprite _solid,_playerSprite,_coinSprite,_enemySprite;GameObject _player,_resultPanel;
        TextMeshPro _scoreText,_livesText,_timeText,_dashText,_message,_preview;Canvas _overlay;AudioSource _audio;AudioClip _coinClip,_hitClip;
        Vector2 _playerPos;int _score,_lives,_coinChain,_bestChain;float _time,_invincibleUntil,_dashReadyAt,_dashUntil,_worldY,_lastCoinAt;bool _active,_ended;

        void Awake(){_worldY=GetComponent<ArcadeMachineInteractable>()?.MachineId=="arcade-14"?WorldY+5000f:WorldY;LoadAssets();CreateScreen();Build();PreparePreview();Show(false);InteractionFocusCamera.Released+=Released;enabled=false;}
        public bool Begin(){if(_camera==null||_screenMaterial==null||_playerSprite==null||_coinSprite==null||_enemySprite==null)return false;ArcadeOverlayHudSuppressor.Acquire();NewGame();Show(true);_active=true;enabled=true;return true;}
        void Update(){if(!_active)return;if(!InteractionFocusCamera.IsFocused){Released();return;}if(_ended){if(ArcadeRetryInput.WasPressed())NewGame();return;}_time-=Time.deltaTime;if(_time<=0){Finish(false);return;}_timeText.text=Mathf.CeilToInt(_time).ToString();
            Vector2 input=new((Input.GetKey(KeyCode.D)||Input.GetKey(KeyCode.RightArrow)?1:0)-(Input.GetKey(KeyCode.A)||Input.GetKey(KeyCode.LeftArrow)?1:0),(Input.GetKey(KeyCode.W)||Input.GetKey(KeyCode.UpArrow)?1:0)-(Input.GetKey(KeyCode.S)||Input.GetKey(KeyCode.DownArrow)?1:0));
            if(Input.GetKeyDown(KeyCode.Space)&&Time.time>=_dashReadyAt&&input.sqrMagnitude>.01f){_dashUntil=Time.time+.2f;_dashReadyAt=Time.time+2f;_invincibleUntil=Mathf.Max(_invincibleUntil,_dashUntil);}
            float speed=Time.time<_dashUntil?12.5f:5.2f;MovePlayer(Vector2.ClampMagnitude(input,1)*speed*Time.deltaTime);MoveEnemies();CollectCoins();CheckEnemyHit();_dashText.text=Time.time>=_dashReadyAt?"SPACE DASH: READY":$"DASH: {Mathf.Max(0,_dashReadyAt-Time.time):0.0}s";_player.GetComponent<SpriteRenderer>().color=Time.time<_invincibleUntil&&Mathf.FloorToInt(Time.time*12)%2==0?new Color(.3f,1f,1f,.38f):Color.white;}
        void MovePlayer(Vector2 delta){Vector2 next=_playerPos+delta;if(!Blocked(new Vector2(next.x,_playerPos.y),.3f))_playerPos.x=next.x;if(!Blocked(new Vector2(_playerPos.x,next.y),.3f))_playerPos.y=next.y;_player.transform.position=ToWorld(_playerPos);}
        void MoveEnemies(){foreach(var e in _enemies){float distance=Vector2.Distance(_playerPos,e.Pos);Vector2 desired=distance<3.25f?(_playerPos-e.Pos).normalized:e.Velocity.normalized;float speed=distance<3.25f?1.55f:1.05f;Vector2 tryX=e.Pos+new Vector2(desired.x,0)*speed*Time.deltaTime;Vector2 tryY=e.Pos+new Vector2(0,desired.y)*speed*Time.deltaTime;if(!Blocked(tryX,.27f))e.Pos.x=tryX.x;else if(!Blocked(tryY,.27f))e.Pos.y=tryY.y;else e.Velocity=-e.Velocity;e.Go.transform.position=ToWorld(e.Pos);e.Go.transform.Rotate(0,0,110*Time.deltaTime);}}
        bool Blocked(Vector2 p,float radius){if(Mathf.Abs(p.x)>5.55f-radius||Mathf.Abs(p.y)>3.55f-radius)return true;foreach(var w in _walls)if(p.x+radius>w.xMin&&p.x-radius<w.xMax&&p.y+radius>w.yMin&&p.y-radius<w.yMax)return true;return false;}
        void CollectCoins(){for(int i=_coins.Count-1;i>=0;i--){var c=_coins[i];if(Vector2.Distance(_playerPos,Local(c.transform.position))>.48f)continue;Destroy(c);_coins.RemoveAt(i);_coinChain=Time.time-_lastCoinAt<2.4f?_coinChain+1:1;_lastCoinAt=Time.time;_bestChain=Mathf.Max(_bestChain,_coinChain);_score+=500+Mathf.Min(1000,_coinChain*100);if(_coinChain%5==0){_time+=3f;_dashReadyAt=Time.time;_message.text=$"COIN RUSH x{_coinChain}! +3s\nDASH RECHARGED";StartCoroutine(ClearMessage());}_scoreText.text=_score.ToString("N0");Play(_coinClip,.4f);if(_coins.Count==0)Finish(true);}}
        void CheckEnemyHit(){if(Time.time<_invincibleUntil)return;foreach(var e in _enemies)if(Vector2.Distance(_playerPos,e.Pos)<.48f){_lives--;_livesText.text="LIVES "+_lives;Vector2 push=(e.Pos-_playerPos).normalized;e.Pos+=push*1.35f;e.Go.transform.position=ToWorld(e.Pos);_playerPos=new Vector2(-4.8f,-2.9f);_player.transform.position=ToWorld(_playerPos);_invincibleUntil=Time.time+2.4f;Play(_hitClip,.45f);if(_lives<=0)Finish(false);return;}}
        void NewGame(){StopAllCoroutines();ClearRound();_score=0;_lives=3;_coinChain=_bestChain=0;_lastCoinAt=-99f;_time=75;_ended=false;_scoreText.text="0";_livesText.text="LIVES 3";_timeText.text="75";_dashReadyAt=Time.time;_invincibleUntil=Time.time+3f;_preview.gameObject.SetActive(false);_resultPanel.SetActive(false);_message.text="GET 15 COINS TO ESCAPE!\nCHAIN COINS FOR TIME + DASH\nSPACE TO DASH";_playerPos=new Vector2(-4.8f,-2.9f);_player.transform.position=ToWorld(_playerPos);_player.SetActive(true);SpawnRound();StartCoroutine(ClearMessage());}
        IEnumerator ClearMessage(){yield return new WaitForSeconds(1.5f);if(!_ended)_message.text=string.Empty;}
        void SpawnRound(){Vector2[] spots={new(-4.6f,2.8f),new(-2.4f,2.8f),new(0,2.8f),new(2.4f,2.8f),new(4.6f,2.8f),new(-3.5f,.7f),new(-.9f,.7f),new(1.4f,.7f),new(4.2f,.7f),new(-4.1f,-1.4f),new(-1.7f,-1.4f),new(1.2f,-1.4f),new(3.8f,-1.4f),new(0,-3f),new(4.5f,-3f)};foreach(var p in spots){var c=SpriteObject("Coin",_coinSprite,new Color(1,.85f,.15f),p,5);SetHeight(c,.48f);_coins.Add(c);}SpawnEnemy(new Vector2(4.6f,2.7f),new Vector2(-1,0));SpawnEnemy(new Vector2(3.9f,-2.8f),new Vector2(0,1));}
        void SpawnEnemy(Vector2 p,Vector2 v){var g=SpriteObject("Sentinel",_enemySprite,new Color(1,.25f,.45f),p,6);SetHeight(g,.72f);_enemies.Add(new Enemy{Go=g,Pos=p,Velocity=v*2});}
        void Finish(bool won){_ended=true;_player.SetActive(false);_message.text=string.Empty;_resultPanel.SetActive(true);_preview.gameObject.SetActive(true);ArcadeRankingBoard.ShowResult(this,_preview,_camera,"NEON MAZE",$"{(won?"MAZE CLEAR!":"GAME OVER")}   SCORE {_score:N0}\nBEST COIN RUSH x{_bestChain}",_score);}
        void Build(){_solid=Solid();var cg=Track(new GameObject("@MazeCamera"));_camera=cg.AddComponent<Camera>();_camera.orthographic=true;_camera.orthographicSize=4.5f;_camera.aspect=16f/9f;_camera.clearFlags=CameraClearFlags.SolidColor;_camera.backgroundColor=new Color(.018f,.025f,.07f);_camera.transform.position=new Vector3(0,_worldY,-10);_target=new RenderTexture(640,360,16){name="NeonMaze_640x360",filterMode=FilterMode.Bilinear};_target.Create();_camera.targetTexture=_target;
            Panel(new Vector2(6.15f,0),new Vector2(1.7f,8.2f),new Color(.06f,.1f,.22f),-2);Text("NEON\nMAZE",new Vector2(6.15f,3.2f),4.1f,new Color(.35f,1f,.85f),out _);Text("SCORE",new Vector2(6.15f,1.8f),2.5f,Color.white,out _);Text("0",new Vector2(6.15f,1.25f),3.8f,new Color(1,.8f,.2f),out _scoreText);Text("TIME",new Vector2(6.15f,.25f),2.4f,Color.white,out _);Text("75",new Vector2(6.15f,-.3f),3.8f,new Color(.4f,1f,.9f),out _timeText);Text("LIVES 3",new Vector2(6.15f,-1.35f),2.8f,new Color(1,.4f,.55f),out _livesText);Text("SPACE DASH: READY",new Vector2(6.15f,-2.55f),1.8f,new Color(.35f,1f,.85f),out _dashText);Text("WASD MOVE",new Vector2(6.15f,-3.2f),1.8f,new Color(.75f,.82f,.95f),out _);Text("",new Vector2(-.5f,0),3.3f,Color.white,out _message);_resultPanel=Panel(new Vector2(-.5f,-.2f),new Vector2(6.2f,4.0f),new Color(.01f,.02f,.07f,.94f),18);Text("",new Vector2(-.5f,-.2f),3f,Color.white,out _preview);
            AddWall(new Rect(-3.8f,1.6f,2.2f,.28f));AddWall(new Rect(-.5f,1.6f,2.5f,.28f));AddWall(new Rect(2.7f,1.6f,1.7f,.28f));AddWall(new Rect(-5.6f,-.25f,2.2f,.28f));AddWall(new Rect(-2.2f,-.25f,2.7f,.28f));AddWall(new Rect(1.8f,-.25f,2.4f,.28f));AddWall(new Rect(-3.5f,-2.05f,2.5f,.28f));AddWall(new Rect(.1f,-2.05f,2.2f,.28f));AddWall(new Rect(3.2f,-2.05f,1.3f,.28f));AddWall(new Rect(-.15f,.55f,.28f,1.85f));AddWall(new Rect(2.65f,-1.15f,.28f,1.8f));
            _player=SpriteObject("Player",_playerSprite,Color.white,new Vector2(-4.8f,-2.9f),7);SetHeight(_player,.78f);BuildOverlay();_audio=Track(new GameObject("MazeAudio")).AddComponent<AudioSource>();}
        void AddWall(Rect r){_walls.Add(r);Panel(r.center,r.size,new Color(.2f,.72f,1f),1);}
        void PreparePreview(){ClearRound();_player.SetActive(true);_player.transform.position=ToWorld(new Vector2(-3.7f,-2.5f));_scoreText.text="0";_timeText.text="75";_livesText.text="ARCADE 04";_message.text=string.Empty;_resultPanel.SetActive(true);_preview.gameObject.SetActive(true);ArcadeRankingBoard.ShowPreview(this,_preview,_camera,"NEON MAZE");}
        void DestroyTracked(GameObject g){if(g==null)return;_runtime.Remove(g);Destroy(g);}void ClearRound(){foreach(var c in _coins)if(c!=null)DestroyTracked(c);_coins.Clear();foreach(var e in _enemies)if(e.Go!=null)DestroyTracked(e.Go);_enemies.Clear();}
        void LoadAssets(){_playerSprite=Resources.Load<Sprite>(Root+"Player");_coinSprite=Resources.Load<Sprite>(Root+"Coin");_enemySprite=Resources.Load<Sprite>(Root+"Enemy");_coinClip=Resources.Load<AudioClip>(Root+"Coin");_hitClip=Resources.Load<AudioClip>(Root+"Hit");}void Play(AudioClip c,float v){if(c!=null)_audio.PlayOneShot(c,v);}
        void CreateScreen(){var power=GetComponent<ArcadeScreenPower>();foreach(var r in GetComponentsInChildren<MeshRenderer>(true)){var ms=r.sharedMaterials;for(int i=0;i<ms.Length;i++)if(ms[i]!=null&&power!=null&&power.IsScreenMaterial(ms[i])){_screenMaterial=new Material(ms[i]);_screenMaterial.SetTextureScale("_BaseMap",Vector2.one);_screenMaterial.SetTextureOffset("_BaseMap",Vector2.zero);ms[i]=_screenMaterial;r.sharedMaterials=ms;return;}}}
        void BuildOverlay(){var go=Track(new GameObject("@MazePlayCanvas",typeof(RectTransform),typeof(Canvas),typeof(CanvasScaler),typeof(GraphicRaycaster)));_overlay=go.GetComponent<Canvas>();_overlay.renderMode=RenderMode.ScreenSpaceOverlay;_overlay.sortingOrder=32000;var sc=go.GetComponent<CanvasScaler>();sc.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;sc.referenceResolution=new Vector2(1920,1080);sc.matchWidthOrHeight=.5f;var back=new GameObject("Backdrop",typeof(RectTransform),typeof(Image));back.transform.SetParent(go.transform,false);var br=back.GetComponent<RectTransform>();br.anchorMin=Vector2.zero;br.anchorMax=Vector2.one;br.offsetMin=br.offsetMax=Vector2.zero;back.GetComponent<Image>().color=Color.black;var image=new GameObject("GameScreen",typeof(RectTransform),typeof(RawImage),typeof(AspectRatioFitter));image.transform.SetParent(go.transform,false);var rect=image.GetComponent<RectTransform>();rect.anchorMin=Vector2.zero;rect.anchorMax=Vector2.one;rect.offsetMin=rect.offsetMax=Vector2.zero;image.GetComponent<RawImage>().texture=_target;var fit=image.GetComponent<AspectRatioFitter>();fit.aspectMode=AspectRatioFitter.AspectMode.FitInParent;fit.aspectRatio=16f/9f;}
        void Show(bool play){if(_overlay!=null)_overlay.gameObject.SetActive(play);if(_screenMaterial!=null)_screenMaterial.SetTexture("_BaseMap",_target);if(_preview!=null)_preview.gameObject.SetActive(!play);if(_camera!=null){_camera.enabled=play;if(!play)_camera.Render();}}void Released(){if(!_active)return;_active=false;StopAllCoroutines();CancelInvoke();ArcadeOverlayHudSuppressor.Release();PreparePreview();Show(false);enabled=false;}
        GameObject SpriteObject(string n,Sprite s,Color c,Vector2 p,int o){var g=Track(new GameObject(n));g.transform.position=ToWorld(p);var r=g.AddComponent<SpriteRenderer>();r.sprite=s??_solid;r.color=c;r.sortingOrder=o;return g;}GameObject Panel(Vector2 p,Vector2 size,Color c,int o){var g=SpriteObject("Panel",_solid,c,p,o);g.transform.localScale=new Vector3(size.x,size.y,1);return g;}void Text(string v,Vector2 p,float size,Color c,out TextMeshPro t){var g=Track(new GameObject("Text"));g.transform.position=ToWorld(p);t=g.AddComponent<TextMeshPro>();t.text=v;t.fontSize=size;t.color=c;t.alignment=TextAlignmentOptions.Center;t.rectTransform.sizeDelta=new Vector2(7,5);t.sortingOrder=20;}Sprite Solid(){var t=new Texture2D(1,1);t.SetPixel(0,0,Color.white);t.Apply();return Sprite.Create(t,new Rect(0,0,1,1),Vector2.one*.5f,1);}static void SetHeight(GameObject g,float h){var s=g.GetComponent<SpriteRenderer>().sprite;g.transform.localScale=Vector3.one*(h/Mathf.Max(.001f,s.bounds.size.y));}GameObject Track(GameObject g){g.transform.SetParent(null,false);_runtime.Add(g);return g;}Vector3 ToWorld(Vector2 p)=>new(p.x,_worldY+p.y,0);Vector2 Local(Vector3 p)=>new(p.x,p.y-_worldY);
        void OnDestroy(){if(_active)ArcadeOverlayHudSuppressor.Release();InteractionFocusCamera.Released-=Released;foreach(var g in _runtime)if(g!=null)Destroy(g);if(_target!=null){_target.Release();Destroy(_target);}if(_screenMaterial!=null)Destroy(_screenMaterial);}
    }
}
