// 10·20번 오락기에서 움직이는 블록의 겹친 부분만 남기며 탑을 쌓는 타이밍 게임을 실행한다.
using System.Collections;
using System.Collections.Generic;
using Festa.World;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Festa.Content.Arcade
{
    [DisallowMultipleComponent]
    public sealed class MegaPackNeonStackMiniGame : MonoBehaviour
    {
        const float BaseWorldY=11000f,BlockHeight=.48f,StartWidth=5.2f;const string Root="Arcade/MegaPackNeonStack/";
        readonly List<GameObject> _runtime=new(),_tower=new();static readonly Color[] Palette={new(.2f,1f,.9f),new(.35f,.45f,1f),new(.8f,.3f,1f),new(1f,.35f,.58f),new(1f,.72f,.2f)};
        Camera _camera;RenderTexture _target;Material _screenMaterial;Sprite _solid,_blockSprite;AudioClip _hit,_perfect;AudioSource _audio;Canvas _overlay;GameObject _moving,_resultPanel;TextMeshPro _scoreText,_heightText,_comboText,_phaseText,_message,_preview;
        float _worldY,_movingX,_movingWidth,_topX,_topWidth,_direction,_speed,_baseY,_shake;int _height,_score,_combo,_bestCombo,_safety;bool _active,_ended;

        void Awake(){_worldY=GetComponent<ArcadeMachineInteractable>()?.MachineId=="arcade-20"?BaseWorldY+5000f:BaseWorldY;LoadAssets();CreateScreen();Build();PreparePreview();Show(false);InteractionFocusCamera.Released+=Released;enabled=false;}
        public bool Begin(){if(_camera==null||_screenMaterial==null||_blockSprite==null)return false;ArcadeRuntimeSuspension.Resume(_runtime);ArcadeOverlayHudSuppressor.Acquire();enabled=true;NewGame();Show(true);_active=true;return true;}
        void Update(){if(!_active)return;if(!InteractionFocusCamera.IsFocused){Released();return;}if(_shake>0){_shake-=Time.deltaTime;_camera.transform.position=new Vector3(Random.Range(-.07f,.07f),_worldY+Random.Range(-.05f,.05f),-10);}else _camera.transform.position=new Vector3(0,_worldY,-10);if(_ended){if(ArcadeRetryInput.WasPressed())NewGame();return;}float pulse=1f+Mathf.Sin(Time.time*(2.5f+_height*.12f))*.12f;_movingX+=_direction*_speed*pulse*Time.deltaTime;if(_movingX>5.25f-_movingWidth*.5f){_movingX=5.25f-_movingWidth*.5f;_direction=-1;}else if(_movingX<-5.25f+_movingWidth*.5f){_movingX=-5.25f+_movingWidth*.5f;_direction=1;}_moving.transform.position=ToWorld(new Vector2(_movingX,CurrentY()));if(Input.GetKeyDown(KeyCode.Space)||Input.GetKeyDown(KeyCode.Return))Drop();}
        void NewGame(){StopAllCoroutines();ClearTower();_height=_score=_combo=_bestCombo=0;_safety=1;_baseY=-3.25f;_topX=0;_topWidth=StartWidth;_ended=false;_resultPanel.SetActive(false);_preview.gameObject.SetActive(false);var foundation=MakeBlock("Foundation",0,_baseY,StartWidth,Palette[0],5);_tower.Add(foundation);_message.text="ENDLESS TOWER\nPERFECT x3 EARNS A SAFETY";StartCoroutine(ClearMessage());SpawnMover();UpdateHud();}
        IEnumerator ClearMessage(){yield return new WaitForSeconds(1.45f);if(!_ended)_message.text=string.Empty;}
        void SpawnMover(){_movingWidth=_topWidth;_direction=_height%2==0?1:-1;_movingX=_direction>0?-5.25f+_movingWidth*.5f:5.25f-_movingWidth*.5f;_speed=Mathf.Min(10.8f,3.15f+_height*.31f);_moving=MakeBlock("MovingBlock",_movingX,CurrentY(),_movingWidth,Palette[(_height+1)%Palette.Length],9);}
        void Drop(){float left=Mathf.Max(_movingX-_movingWidth*.5f,_topX-_topWidth*.5f),right=Mathf.Min(_movingX+_movingWidth*.5f,_topX+_topWidth*.5f),overlap=right-left;_shake=.12f;if(overlap<=.035f){StartCoroutine(FallPiece(_moving,_direction*2.1f));_moving=null;if(_safety>0){_safety--;_combo=0;_score=Mathf.Max(0,_score-250);_topWidth=Mathf.Max(.7f,_topWidth*.72f);ScaleBlock(_tower[^1],_topWidth);_message.text="SAFETY CRANE!";StartCoroutine(ClearMessage());SpawnMover();UpdateHud();return;}Finish();return;}float center=(left+right)*.5f;bool perfect=Mathf.Abs(_movingX-_topX)<.085f;if(perfect){center=_topX;overlap=_topWidth;_combo++;_score+=500+_combo*125;Play(_perfect,.55f);StartCoroutine(FlashPerfect());StartCoroutine(Sparks(center,CurrentY(),Palette[(_height+1)%Palette.Length],10));if(_combo%3==0)_safety=Mathf.Min(2,_safety+1);}else{_combo=0;_score+=Mathf.RoundToInt(240f*overlap/StartWidth);Play(_hit,.3f);CreateCutPiece(left,right);}_bestCombo=Mathf.Max(_bestCombo,_combo);_movingX=center;_movingWidth=overlap;ScaleBlock(_moving,overlap);_moving.transform.position=ToWorld(new Vector2(center,CurrentY()));_tower.Add(_moving);_topX=center;_topWidth=overlap;_height++;if(_height%5==0){_topWidth=Mathf.Min(StartWidth,_topWidth+.42f);ScaleBlock(_tower[^1],_topWidth);_score+=1000;StartCoroutine(Checkpoint());}if(_height>11)ShiftTowerDown();SpawnMover();UpdateHud();}
        void CreateCutPiece(float keepLeft,float keepRight){float originalLeft=_movingX-_movingWidth*.5f,originalRight=_movingX+_movingWidth*.5f;if(originalLeft<keepLeft){float w=keepLeft-originalLeft;var cut=MakeBlock("CutPiece",originalLeft+w*.5f,CurrentY(),w,Palette[(_height+1)%Palette.Length],8);StartCoroutine(FallPiece(cut,-1.2f));}if(originalRight>keepRight){float w=originalRight-keepRight;var cut=MakeBlock("CutPiece",keepRight+w*.5f,CurrentY(),w,Palette[(_height+1)%Palette.Length],8);StartCoroutine(FallPiece(cut,1.2f));}}
        IEnumerator FallPiece(GameObject g,float drift){float t=0;var start=g.transform.position;while(t<.65f&&g!=null){t+=Time.deltaTime;g.transform.position=start+new Vector3(drift*t,-7f*t*t,0);g.transform.Rotate(0,0,180f*Time.deltaTime);yield return null;}DestroyTracked(g);}
        IEnumerator FlashPerfect(){_message.text=_combo%3==0?"PERFECT x3!  +SAFETY":"PERFECT!";yield return new WaitForSeconds(.48f);if(!_ended)_message.text=string.Empty;}
        IEnumerator Checkpoint(){_message.text=$"FLOOR {_height} CHECKPOINT!\nWIDTH BOOST";for(int i=0;i<18;i++)StartCoroutine(Sparks(Random.Range(-3.5f,3.5f),Random.Range(-1f,3f),Palette[Random.Range(0,Palette.Length)],1));yield return new WaitForSeconds(.72f);if(!_ended)_message.text=string.Empty;}
        IEnumerator Sparks(float x,float y,Color color,int count){for(int i=0;i<count;i++){var g=Panel(new Vector2(x,y),new Vector2(.07f,.07f),color,14);var velocity=new Vector2(Random.Range(-2.2f,2.2f),Random.Range(1.2f,3.8f));float t=0;while(t<.48f&&g!=null){t+=Time.deltaTime;velocity.y-=7f*Time.deltaTime;g.transform.position+=new Vector3(velocity.x,velocity.y,0)*Time.deltaTime;yield return null;}DestroyTracked(g);}}
        void ShiftTowerDown(){for(int i=_tower.Count-1;i>=0;i--){var g=_tower[i];if(g==null){_tower.RemoveAt(i);continue;}g.transform.position+=Vector3.down*BlockHeight;if(i<_tower.Count-1&&g.transform.position.y<_worldY-4.6f){_tower.RemoveAt(i);DestroyTracked(g);}}_baseY-=BlockHeight;}
        float CurrentY()=>_baseY+(_height+1)*BlockHeight;void UpdateHud(){_scoreText.text=_score.ToString("N0");_heightText.text=$"FLOOR {_height}\nWIDTH {Mathf.RoundToInt(_topWidth/StartWidth*100)}%";_comboText.text=_combo>1?$"PERFECT x{_combo}":"COMBO -";_phaseText.text=$"{(_height<5?"WARM UP":_height<10?"SPEED UP":_height<15?"PULSE ZONE":$"ENDLESS x{1+(_height-15)/10}")}\nSAFETY {_safety}/2";}
        void Finish(){_ended=true;_message.text=string.Empty;if(_moving!=null){DestroyTracked(_moving);_moving=null;}_resultPanel.SetActive(true);_preview.gameObject.SetActive(true);ArcadeRankingBoard.ShowResult(this,_preview,_camera,"NEON STACK",$"TOWER FALL!   SCORE {_score:N0}\nHEIGHT {_height}   BEST PERFECT {_bestCombo}",_score);}
        void Build(){_solid=Solid();var cg=Track(new GameObject("@NeonStackCamera"));_camera=cg.AddComponent<Camera>();_camera.orthographic=true;_camera.orthographicSize=4.5f;_camera.aspect=16f/9f;_camera.clearFlags=CameraClearFlags.SolidColor;_camera.backgroundColor=new Color(.018f,.015f,.065f);_camera.transform.position=new Vector3(0,_worldY,-10);_target=new RenderTexture(640,360,16){name="NeonStack_640x360",filterMode=FilterMode.Bilinear};_target.Create();_camera.targetTexture=_target;
            for(int i=0;i<30;i++){float x=Random.Range(-5.5f,5.2f),y=Random.Range(-3.8f,3.9f);Panel(new Vector2(x,y),new Vector2(.035f,.035f),new Color(.4f,.75f,1,Random.Range(.25f,.8f)),0);}for(int i=0;i<7;i++)Panel(new Vector2(-5.45f+i*1.7f,-3.72f),new Vector2(1.35f,Random.Range(.35f,1.45f)),new Color(.035f,.08f,.16f),1);Panel(new Vector2(6.15f,0),new Vector2(1.75f,8.2f),new Color(.055f,.05f,.2f),3);Text("NEON\nSTACK",new Vector2(6.15f,3.1f),3.7f,new Color(.4f,1f,.9f),out _);Text("SCORE",new Vector2(6.15f,1.65f),2.2f,Color.white,out _);Text("0",new Vector2(6.15f,1.12f),3.5f,new Color(1,.82f,.2f),out _scoreText);Text("FLOOR 0\nWIDTH 100%",new Vector2(6.15f,.05f),1.9f,Color.white,out _heightText);Text("COMBO -",new Vector2(6.15f,-1.05f),1.85f,new Color(1,.45f,.75f),out _comboText);Text("WARM UP\nSAFETY 1/2",new Vector2(6.15f,-1.85f),1.55f,new Color(.35f,1f,.75f),out _phaseText);Text("SPACE / ENTER\nDROP BLOCK",new Vector2(6.15f,-3.05f),1.55f,new Color(.72f,.84f,1),out _);Text("",new Vector2(-.65f,3.15f),2.5f,Color.white,out _message);_resultPanel=Panel(new Vector2(-.65f,-.05f),new Vector2(7.3f,5.25f),new Color(.01f,.018f,.07f,.97f),18);Text("",new Vector2(-.65f,-.05f),2.15f,Color.white,out _preview);BuildOverlay();_audio=Track(new GameObject("StackAudio")).AddComponent<AudioSource>();}
        GameObject MakeBlock(string name,float x,float y,float width,Color color,int order){var g=SpriteObject(name,_blockSprite,color,new Vector2(x,y),order);ScaleBlock(g,width);return g;}void ScaleBlock(GameObject g,float width){var s=g.GetComponent<SpriteRenderer>().sprite;g.transform.localScale=new Vector3(width/Mathf.Max(.001f,s.bounds.size.x),BlockHeight/Mathf.Max(.001f,s.bounds.size.y),1);}
        void PreparePreview(){ClearTower();if(_moving!=null){DestroyTracked(_moving);_moving=null;}for(int i=0;i<8;i++){float w=StartWidth-i*.34f;_tower.Add(MakeBlock("PreviewBlock",Mathf.Sin(i*.7f)*.22f,-3.2f+i*BlockHeight,w,Palette[i%Palette.Length],5));}_scoreText.text="0";_heightText.text="ENDLESS\nHIGH SCORE";_comboText.text="PERFECT COMBO";_phaseText.text="CHECKPOINTS\nSAFETY CRANE";_message.text=string.Empty;_resultPanel.SetActive(true);_preview.gameObject.SetActive(true);ArcadeRankingBoard.ShowPreview(this,_preview,_camera,"NEON STACK\nDROP • TRIM • CLIMB");}
        void ClearTower(){for(int i=_tower.Count-1;i>=0;i--)DestroyTracked(_tower[i]);_tower.Clear();}
        void DestroyTracked(GameObject g){if(g==null)return;_runtime.Remove(g);Destroy(g);}
        void LoadAssets(){_blockSprite=Resources.Load<Sprite>(Root+"Block");_hit=Resources.Load<AudioClip>(Root+"Hit");_perfect=Resources.Load<AudioClip>(Root+"Perfect");}void Play(AudioClip c,float v){if(c!=null)_audio.PlayOneShot(c,v);}
        void CreateScreen(){var power=GetComponent<ArcadeScreenPower>();foreach(var r in GetComponentsInChildren<MeshRenderer>(true)){var ms=r.sharedMaterials;for(int i=0;i<ms.Length;i++)if(ms[i]!=null&&power!=null&&power.IsScreenMaterial(ms[i])){_screenMaterial=new Material(ms[i]);_screenMaterial.SetTextureScale("_BaseMap",Vector2.one);_screenMaterial.SetTextureOffset("_BaseMap",Vector2.zero);ms[i]=_screenMaterial;r.sharedMaterials=ms;return;}}}
        void BuildOverlay(){var go=Track(new GameObject("@NeonStackPlayCanvas",typeof(RectTransform),typeof(Canvas),typeof(CanvasScaler),typeof(GraphicRaycaster)));_overlay=go.GetComponent<Canvas>();_overlay.renderMode=RenderMode.ScreenSpaceOverlay;_overlay.sortingOrder=32000;var sc=go.GetComponent<CanvasScaler>();sc.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;sc.referenceResolution=new Vector2(1920,1080);sc.matchWidthOrHeight=.5f;var back=new GameObject("Backdrop",typeof(RectTransform),typeof(Image));back.transform.SetParent(go.transform,false);var br=back.GetComponent<RectTransform>();br.anchorMin=Vector2.zero;br.anchorMax=Vector2.one;br.offsetMin=br.offsetMax=Vector2.zero;back.GetComponent<Image>().color=Color.black;var image=new GameObject("GameScreen",typeof(RectTransform),typeof(RawImage),typeof(AspectRatioFitter));image.transform.SetParent(go.transform,false);var rect=image.GetComponent<RectTransform>();rect.anchorMin=Vector2.zero;rect.anchorMax=Vector2.one;rect.offsetMin=rect.offsetMax=Vector2.zero;image.GetComponent<RawImage>().texture=_target;var fit=image.GetComponent<AspectRatioFitter>();fit.aspectMode=AspectRatioFitter.AspectMode.FitInParent;fit.aspectRatio=16f/9f;}
        void Show(bool p){if(_overlay!=null)_overlay.gameObject.SetActive(p);if(_screenMaterial!=null)_screenMaterial.SetTexture("_BaseMap",_target);if(_preview!=null)_preview.gameObject.SetActive(!p);if(_camera!=null){_camera.enabled=p;if(!p)_camera.Render();}if(!p)ArcadeRuntimeSuspension.Suspend(_runtime);}void Released(){if(!_active)return;_active=false;StopAllCoroutines();CancelInvoke();ArcadeOverlayHudSuppressor.Release();if(_preview!=null){PreparePreview();Show(false);}enabled=false;}
        GameObject SpriteObject(string n,Sprite s,Color c,Vector2 p,int o){var g=Track(new GameObject(n));g.transform.position=ToWorld(p);var r=g.AddComponent<SpriteRenderer>();r.sprite=s??_solid;r.color=c;r.sortingOrder=o;return g;}GameObject Panel(Vector2 p,Vector2 z,Color c,int o){var g=SpriteObject("Panel",_solid,c,p,o);g.transform.localScale=new Vector3(z.x,z.y,1);return g;}void Text(string v,Vector2 p,float size,Color c,out TextMeshPro t){var g=Track(new GameObject("Text"));g.transform.position=ToWorld(p);t=g.AddComponent<TextMeshPro>();t.text=v;t.fontSize=size;t.color=c;t.alignment=TextAlignmentOptions.Center;t.rectTransform.sizeDelta=new Vector2(8,5);t.sortingOrder=20;}Sprite Solid(){var t=new Texture2D(1,1);t.SetPixel(0,0,Color.white);t.Apply();return Sprite.Create(t,new Rect(0,0,1,1),Vector2.one*.5f,1);}GameObject Track(GameObject g){g.transform.SetParent(null,false);_runtime.Add(g);return g;}Vector3 ToWorld(Vector2 p)=>new(p.x,_worldY+p.y,0);
        void OnDestroy(){if(_active)ArcadeOverlayHudSuppressor.Release();InteractionFocusCamera.Released-=Released;ClearTower();foreach(var g in _runtime)if(g!=null)Destroy(g);if(_target!=null){_target.Release();Destroy(_target);}if(_screenMaterial!=null)Destroy(_screenMaterial);}
    }
}
