-- FE 전체 회귀 실측 (S15P21A604-538) — 로컬 DB 시드
--
-- 실행: docker exec -i ssafesta-local-postgres-1 psql -U ssafesta -d ssafesta -f -
--
-- ## 왜 이렇게 적게 넣는가
--
-- 스키마가 세 개의 유니크 제약으로 묶여 있어 "설문 하나 더" 가 "계정 하나 더" 를 부른다.
--
--   ux_surveys_booth              부스당 설문 1개
--   ux_booths_owner               소유자당 부스 1개
--   ux_booth_leases_active_lessee 사용자당 ACTIVE 임대 1개
--
-- 그래서 설문 상태별로 부스를 늘리는 대신 **booth 1 / survey 1 의 상태를 순서대로 바꿔 가며**
-- 검증하고(마감·잠금·재제출·보상·임대만료), 그것으로 도저히 만들 수 없는 두 가지만 계정을 만든다.
--
--   BOOTH_EDITOR_FORBIDDEN   남의 부스가 있어야 한다        → user 900001 + booth 900001
--   WALLET_NOT_FOUND         지갑 없는 회원이 있어야 한다    → user 900002 (지갑 없음, 의도적)
--
-- ## id 대역
--
-- 전부 900001+ 를 명시한다(GENERATED BY DEFAULT 라 가능). 시퀀스를 건드리지 않고,
-- 정리할 때 "내가 만든 행" 을 대역 하나로 특정할 수 있다. 이름에도 E2E0908- 표식을 박는다.
--
-- ## 지갑을 손으로 만드는 이유와 그 위험 (LJH T-60)
--
-- users 행만 넣으면 도메인이 깨진다 — RegistrationService.createMember() 가 같은 트랜잭션에서
-- WalletService.openWallet() 을 부르고, 그것이 지갑과 가입 지급 원장(CHARGE / INITIAL_GRANT /
-- 멱등키 INITIAL_GRANT:<userId> / 200코인)을 함께 만든다. user 900001 은 그 모양을 그대로 따른다.
-- user 900002 는 **일부러 그 절차를 건너뛴다** — WALLET_NOT_FOUND 가 그 상태를 보는 케이스다.

-- ============================================================
-- [0] 시작 대조표 — 시드 전에 찍어 두고 Phase 6 에서 같은 쿼리로 대조한다
-- ============================================================
-- SELECT 'users' t, count(*) n FROM users
-- UNION ALL SELECT 'booths', count(*) FROM booths
-- UNION ALL SELECT 'booth_leases', count(*) FROM booth_leases
-- UNION ALL SELECT 'wallets', count(*) FROM wallets
-- UNION ALL SELECT 'coin_ledger_entries', count(*) FROM coin_ledger_entries
-- UNION ALL SELECT 'surveys', count(*) FROM surveys
-- UNION ALL SELECT 'survey_questions', count(*) FROM survey_questions
-- UNION ALL SELECT 'survey_options', count(*) FROM survey_options
-- UNION ALL SELECT 'survey_responses', count(*) FROM survey_responses
-- UNION ALL SELECT 'survey_answers', count(*) FROM survey_answers
-- ORDER BY 1;

BEGIN;

-- ============================================================
-- [1] user 900001 — 남의 부스 주인. BOOTH_EDITOR_FORBIDDEN 용
--     RegistrationService.createMember() 와 같은 모양: users + wallets + INITIAL_GRANT 원장
-- ============================================================
INSERT INTO users (id, account_type, nickname, status)
VALUES (900001, 'MEMBER', 'E2E0908-u1', 'ACTIVE');

INSERT INTO wallets (id, user_id, balance)
VALUES (900001, 900001, 200);

INSERT INTO coin_ledger_entries
    (id, wallet_id, entry_type, amount, balance_after, reason_type, idempotency_key)
VALUES
    (900001, 900001, 'CHARGE', 200, 200, 'INITIAL_GRANT', 'INITIAL_GRANT:900001');

-- 부스와 임대. 슬롯 12는 AVAILABLE 이었다(슬롯 1은 booth 1 이 쓴다).
INSERT INTO booths (id, owner_user_id, current_slot_id, name, status)
VALUES (900001, 900001, 12, 'E2E0908-남의부스', 'ACTIVE');

INSERT INTO booth_leases
    (id, booth_id, slot_id, lessee_user_id, status, starts_at, ends_at, charged_coin)
VALUES
    (900001, 900001, 12, 900001, 'ACTIVE', now() - interval '1 day', now() + interval '30 days', 0);

UPDATE booth_slots SET status = 'OCCUPIED' WHERE id = 12;

-- 이 부스의 설문. 보상 > 0 이라 게스트 제출이 403 MEMBER_ONLY 가 된다.
INSERT INTO surveys (id, booth_id, title, description, reward_coin, status, created_by_user_id)
VALUES (900001, 900001, 'E2E0908-남의 설문', NULL, 5, 'OPEN', 900001);

INSERT INTO survey_questions
    (id, survey_id, question_type, question_text, is_required, display_order)
VALUES
    (900001, 900001, 'SHORT_TEXT', 'E2E0908-남의 문항', false, 0);

-- ============================================================
-- [2] user 900002 — **지갑이 없는 회원.** WALLET_NOT_FOUND 재현용
--     계약이 "가입 트랜잭션에서 열리므로 깨진 상태다. 조용히 넘기지 않는다" 로 규정한 그 상태를
--     의도적으로 만든다. 부스도 임대도 주지 않는다.
-- ============================================================
INSERT INTO users (id, account_type, nickname, status)
VALUES (900002, 'MEMBER', 'E2E0908-u2-nowallet', 'ACTIVE');

COMMIT;

-- ============================================================
-- [3] 정리 — Phase 6. **900001+ 대역만 지운다.** 기존 행(user 1 / booth 1 / survey 1)은 건드리지 않는다.
--     FK 역순으로 지운다.
-- ============================================================
-- BEGIN;
-- DELETE FROM survey_answer_options WHERE answer_id IN
--     (SELECT a.id FROM survey_answers a JOIN survey_responses r ON r.id = a.response_id
--       WHERE r.survey_id >= 900000);
-- DELETE FROM survey_answers WHERE response_id IN
--     (SELECT id FROM survey_responses WHERE survey_id >= 900000);
-- DELETE FROM survey_responses WHERE survey_id >= 900000;
-- DELETE FROM survey_options   WHERE question_id >= 900000;
-- DELETE FROM survey_questions WHERE survey_id >= 900000;
-- DELETE FROM surveys          WHERE id >= 900000;
-- UPDATE booth_slots SET status = 'AVAILABLE' WHERE id = 12;
-- DELETE FROM booth_leases WHERE id >= 900000;
-- DELETE FROM booths       WHERE id >= 900000;
-- DELETE FROM coin_ledger_entries WHERE id >= 900000;
-- DELETE FROM wallets      WHERE id >= 900000;
-- DELETE FROM users        WHERE id >= 900000;
-- COMMIT;
--
-- 이 밖에 booth 1 / survey 1 을 검증 중에 바꾼 것(ends_at·reward_coin·문항 구조·응답 행)은
-- 이 파일이 아니라 결과 문서 fe-full-regression-0908.md 의 "원복" 절이 추적한다 —
-- 그 변경들은 API 로 냈고 API 로 되돌리는 것이 맞기 때문이다.
